# 1.Python Keywords and Identifiers

## 1a. Python keywords

Python Keywords
Keywords are the reserved words in Python.

We cannot use a keyword as a variable name, function name or any other identifier. They are used to define the syntax and structure of the Python language.

In Python, keywords are case sensitive.

There are 33 keywords in Python 3.7. This number can vary slightly over the course of time.

All the keywords except True, False and None are in lowercase and they must be written as they are. The list of all the keywords is given below.

False	await	else	import	pass None	break	except	in	raise True	class	finally	is	return and	continue	for	lambda	try as	def	from nonlocal	while assert	del	global	not	with async	elif	if	or	yield

## 1b. Python Identifiers

Python Identifiers

An identifier is a name given to entities like class, functions, variables, etc. It helps to differentiate one entity from another.

Rules for writing identifiers

1. Identifiers can be a combination of letters in lowercase (a to z) or uppercase (A to Z) or digits (0 to 9) or an underscore _. Names like myClass, var_1 and print_this_to_screen, all are valid example.

2. An identifier cannot start with a digit. 1variable is invalid, but variable1 is a valid name.

3. Keywords cannot be used as identifiers.
global = 1

4. We cannot use special symbols like !, @, #, $, % etc. in our identifier

5. An identifier can be of any length.

Things to Remember
Python is a case-sensitive language. This means, Variable and variable are not the same.

Always give the identifiers a name that makes sense. While c = 10 is a valid name, writing count = 10 would make more sense, and it would be easier to figure out what it represents when you look at your code after a long gap.

Multiple words can be separated using an underscore, like this_is_a_long_variable.


## 1c. Python variables

1. Variables are labels attached to objects; they are not the object itself. Theyare not containers for objects either. A variable does not contain the object, rather it acts as a pointer or reference to an object. 

2. There is no need to declare the data type of a variable as done in java programming. 

3. Variable name cannot start with an integer/number 

4. Python is case-sensitive in case of variable name 


In [2]:
a = [1,2,3,4]
b=a
a.append(5)
print(a,b)

[1, 2, 3, 4, 5] [1, 2, 3, 4, 5]


5. Here we have created a variable, a, which points to a list object. We create another variable, b, which points to this same list object. When we append an element to this list object, this change is reflected in both a and b.

6. Python is a dynamically typed language. Variable names can be bound to different values and types during program execution. Each value is of a type, a string, or integer for example; however, the name that points to this value does not have a specific type. This is different from many languages such as C and Java where a name represents a fixed size, type, and location in memory. This means when we initialize variables in Python, we do not need to declare a type. Also, variables, or more specifically the objects they point to, can change type depending on the values assigned to them, for example:

In [3]:
a = 1
type(a)

int

In [4]:
a=a+0.1
type(a)

float

# 2.Implicit & Explicit Type Conversion

The process of converting the value of one data type (integer, string, float, etc.) to another data type is called type conversion. Python has two types of type conversion.

Implicit Type Conversion

Explicit Type Conversion

Implicit Type Conversion

In Implicit type conversion, Python automatically converts one data type to another data type. This process doesn't need any user involvement.

Let's see an example where Python promotes the conversion of the lower data type (integer) to the higher data type (float) to avoid data loss.

In [5]:
num_int = 123
num_flo = 1.23

num_new = num_int + num_flo

print("datatype of num_int:",type(num_int))
print("datatype of num_flo:",type(num_flo))

print("Value of num_new:",num_new)
print("datatype of num_new:",type(num_new))

datatype of num_int: <class 'int'>
datatype of num_flo: <class 'float'>
Value of num_new: 124.23
datatype of num_new: <class 'float'>


In the above program,

We add two variables num_int and num_flo, storing the value in num_new.
We will look at the data type of all three objects respectively.
In the output, we can see the data type of num_int is an integer while the data type of num_flo is a float.

Also, we can see the num_new has a float data type because Python always converts smaller data types to larger data types to avoid the loss of data.


In [6]:
#Example 2: Addition of string(higher) data type and integer(lower) datatype
num_int = 123
num_str = "456"

print("Data type of num_int:",type(num_int))
print("Data type of num_str:",type(num_str))

print(num_int+num_str)

Data type of num_int: <class 'int'>
Data type of num_str: <class 'str'>


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In the above program,

We add two variables num_int and num_str.
As we can see from the output, we got TypeError. Python is not able to use Implicit Conversion in such conditions.
However, Python has a solution for these types of situations which is known as Explicit Conversion.

Explicit Type Conversion
In Explicit Type Conversion, users convert the data type of an object to required data type. We use the predefined functions like int(), float(), str(), etc to perform explicit type conversion.

This type of conversion is also called typecasting because the user casts (changes) the data type of the objects.

Syntax :
<required_datatype>(expression)
Typecasting can be done by assigning the required data type function to the expression.

In [7]:
# Example 3: Addition of string and integer using explicit conversion
num_int = 123
num_str = "456"

print("Data type of num_int:",type(num_int))
print("Data type of num_str before Type Casting:",type(num_str))

num_str = int(num_str)
print("Data type of num_str after Type Casting:",type(num_str))

num_sum = num_int + num_str

print("Sum of num_int and num_str:",num_sum)
print("Data type of the sum:",type(num_sum))

Data type of num_int: <class 'int'>
Data type of num_str before Type Casting: <class 'str'>
Data type of num_str after Type Casting: <class 'int'>
Sum of num_int and num_str: 579
Data type of the sum: <class 'int'>


In the above program,

We add num_str and num_int variable.
We converted num_str from string(higher) to integer(lower) type using int() function to perform the addition.
After converting num_str to an integer value, Python is able to add these two variables.
We got the num_sum value and data type to be an integer.

Key Points to Remember
Type Conversion is the conversion of object from one data type to another data type.
Implicit Type Conversion is automatically performed by the Python interpreter.
Python avoids the loss of data in Implicit Type Conversion.
Explicit Type Conversion is also called Type Casting, the data types of objects are converted using predefined functions by the user.
In Type Casting, loss of data may occur as we enforce the object to a specific data type.

# 3.Taking an Input from the User

In [8]:
name = input("Enter your 1st name:")
surname = input("Enter your surname:")
print("Wellcome",name,surname)

Enter your 1st name:Surri
Enter your surname:Singh
Wellcome Surri Singh


Always remember that the input is taken in a string format i.e. str . So if you are taking an integer/ float as an input then typecasting is required for furthur operations 

In [9]:
# take height as input and gove the result as height squared

height = float(input("Enter height in inches:"))
height_sq = height ** 2 
print("The square of height is:",height_sq)

Enter height in inches:23
The square of height is: 529.0


# 4.Escape Characters

In [10]:
print("I have \nalways wanted \nto study") #\n means new line 

I have 
always wanted 
to study


In [11]:
# another way to split string --> USING TRIPLE QUOTATION MARKS

split_string = """I have
always wanted
to study"""
print(split_string)

I have
always wanted
to study


In [12]:
split_string = """I have \
always wanted \
to study"""
print(split_string)

I have always wanted to study


In [13]:
print("I have \t\talways wanted \tto study") #\t gives a tabbed result

I have 		always wanted 	to study


In [14]:
print("The shopkeeper said \" Please come after '3' hours. \"")

The shopkeeper said " Please come after '3' hours. "


In [15]:
print('The shopkeeper said \" Please come after \'3\' hours.\"')

The shopkeeper said " Please come after '3' hours."


In [16]:
print("""The shopkeeper said:"Please come after '3'hours." """)

The shopkeeper said:"Please come after '3'hours." 


In [17]:
print("""The shopkeeper said:"Please come \
after '3'hours." """)

The shopkeeper said:"Please come after '3'hours." 


In [18]:
# print \ within a statement 

print("C:\\users\\newfolder\\tasty") 

C:\users\newfolder\tasty


In [19]:
# OR

print(r"C:\users\newfolder\tasty")  # r stands for raw string 

C:\users\newfolder\tasty


### Note: Python: a strongly typed language?

Python is a STRONGLY TYPED LANGUAGE. This may be confusing because it may seem that Python does not care about the data types since declaration is not required. However in String concatenation it becomes clear that it does recognize data types because Python can only concatenate strings and not a string and an integer ( it does not convert integer to a string since it has been concatenated )

# 5. Built-in Data Types

Python data types can be divided into three categories: numeric, sequence, and mapping. There is also the None object that represents a Null, or absence of a value. It should not be forgotten either that other objects such as classes, files, and exceptions can also properly be considered types; however, they will not be considered here. 

Every value in Python has a data type. Unlike many programming languages, in Python you do not need to explicitly declare the type of a variable. Python keeps track of object types internally.

In [ ]:
Python built-in data types are outlined in the following table:

Category  Name    Description
None      None    The null object.
Numeric   int     Integer.
          float   Floating point number.
          complex Complex number.
          bool    Boolean (True, False).
Sequences str     String of characters.
          list    List of arbitrary objects.
          Tuple   Group of arbitrary items.
          range   Creates a range of integers.
Mapping   dict    Dictionary of key-value pairs.
          set     Mutable, unordered collection of unique items.
       frozenset  Immutable set

## 5a.None Type

None type:  The None type is immutable and has one value, None. It is used to represent the absence of a value. It is returned by objects that do not explicitly return a value and evaluates to False in Boolean expressions. It is often used as the default value in optional arguments to allow the function to detect whether the caller has passed a value.

In [20]:
a = None  # so None is a FALSY value 
bool(a)

False

## 5b.Numeric Types 

Numeric Types:

All numeric types, apart from bool, are signed and they are all immutable. Booleans have two possible values, True and False. These values are mapped to 1 and 0, respectively.

The integer type, int, represents whole numbers of unlimited range.

Floating point numbers are represented by the native double precision floating point representation of the machine. 

Complex numbers are represented by two floating point numbers. They are
assigned using the j operator to signify the imaginary part of the complex number, for example:
a = 2+3j
We can access the real and imaginary parts with a.real and a.imag, respectively.

boolean type - Truthy values v/s Falsy values 
Truthy values : are values that evaluate to TRUE in a boolean context
Falsy values : are values that evaluate to FALSE in the boolean context

Falsy values : empty sequences(lists, tuples, strings, dictionaries, sets), zero in every numeric type , None, and False

Truthy values : include non-empty sequences , numbers (except 0 in every numeric type), and basically what is not falsy. 

They can be used to make the code more precise 

## 5b.1. Representation Error

In [21]:
x=1.0
y=0.9
x-y

0.09999999999999998

In [22]:
1-0.9==0.1

False

It should be noted that the native double precision representation of floating point numbers leads to some unexpected results

This is a result of the fact that most decimal fractions are not exactly representable as a binary fraction, which is how most underlying hardware represents floating point numbers.

For algorithms or applications where this may be an issue, Python provides a decimal module. 

This module allows for the exact representation of decimal numbers and facilitates greater control properties such as rounding behavior, number of significant digits, and precision. 

It defines two objects, a Decimal type, representing decimal numbers, and a
Context type, representing various computational parameters such as precision, rounding, and error handling. An example of its usage can be seen in the following snippet:

In [23]:
import decimal

x = decimal.Decimal(3.145)
y = decimal.Decimal(2.742)

x*y

Decimal('8.623590000000000026361135497')

In [24]:
decimal.getcontext().prec = 4

x*y

Decimal('8.624')

Here we have created a global context and set the precision to 4. The Decimal object can be treated pretty much as you would treat an int or a float. They are subject to all the same mathematical operations and can be used as dictionary keys, placed in sets, and so on. In addition, Decimal objects also have several methods for mathematical operations, such as natural exponents, x.exp(), natural logarithms, x.ln(), and base 10 logarithms, x.log10().

Python also has a fractions module that implements a rational number type. The
following example shows several ways to create fractions:

In [25]:
import fractions

fractions.Fraction(0.5)

Fraction(1, 2)

It is also worth mentioning here the NumPy extension. This has types for mathematical objects such as arrays, vectors, and matrixes, and capabilities for linear algebra, calculation of Fourier transforms, eigenvectors, logical operations, and much more.

NOTE: The maximum float value on a 64 bit computer : move the decimal place 308 places right and the smallest number has 307 zeroes before the decimal place. Python floats have 52 dighits precision which is sufficicent for most purposes.
If more precise decimal numbers are rquired then there is Decimal type.


## 5b.2. Order of precedence of operators

In [ ]:
The operator precedence in Python is listed in the following table. It is in descending order (upper group has higher precedence than the lower ones).

Operators	Meaning
()	Parentheses
**	Exponent
+x, -x, ~x	Unary plus, Unary minus, Bitwise NOT
*, /, //, %	Multiplication, Division, Floor division, Modulus
+, -	Addition, Subtraction
<<, >>	Bitwise shift operators
&	Bitwise AND
^	Bitwise XOR
|	Bitwise OR
==, !=, >, >=, <, <=, is, is not, in, not in	Comparisons, Identity, Membership operators
not	Logical NOT
and	Logical AND
or	Logical OR

### Note: Overview of Data types and Objects 

All data types in Python are objects. In fact, pretty much everything is an object in Python, including modules, classes, and functions, as well as literals such as strings and integers.

Each object in Python has a type, a value, and an identity. When we write greet = "hello world" we are creating an instance of a string object with the value "hello world" and the identity of greet. The identity of an object acts as a pointer to the object's location in memory. The type of an object, also known as the object's class, describes the object's internal representation as well as the methods and operations it supports. Once an instance of an object is created, its identity and type cannot be changed.

We can get the identity of an object by using the built-in function id(). This returns an identifying integer and on most systems this refers to its memory location, although you should not rely on this in any of your code.

Also, there are a number of ways to compare objects, for example:

1. if a== b: #a and b have the same value
2. if a is b: # if a and b are the same object
3. if type(a) is type(b): # a and b are the same type

An important distinction needs to be made between mutable and immutable objects. Mutable object's such as lists can have their values changed. They have methods, such as insert() or append(), that change an objects value. Immutable objects, such as strings,cannot have their values changed, so when we run their methods, they simply return avalue rather than change the value of an underlying object. We can, of course, use this value by assigning it to a variable or using it as an argument in a function.

## 5c. Strings- sequence and immutable

Strings are immutable sequence objects, with each character representing an element in the sequence. As with all objects, we use methods to perform operations. Strings, being immutable, do not change the instance; each method simply returns a value. This value can be stored as another variable or given as an argument to a function or method.

What is String in Python?
A string is a sequence of characters.

A character is simply a symbol. For example, the English language has 26 characters.

Computers do not deal with characters, they deal with numbers (binary). Even though you may see characters on your screen, internally it is stored and manipulated as a combination of 0s and 1s.

This conversion of character to a number is called encoding, and the reverse process is decoding. ASCII and Unicode are some of the popular encodings used.

In Python, a string is a sequence of Unicode characters. Unicode was introduced to include every character in all languages and bring uniformity in encoding. You can learn about Unicode from Python Unicode.

Strings, like all sequence types, support indexing and slicing. We can retrieve any character from a string by using its index s[i]. We can retrieve a slice of a string by using s[i:j], where i and j are the start and end points of the slice. We can return an extended slice by using a stride, as in the following: s[i:j:stride]. 

The following code should make this clear:

## 5c.1 Indexing and Slicing of String object

In [26]:
#Accessing string characters in Python
str = 'programiz'
print('str = ', str)

#first character
print('str[0] = ', str[0])

#last character
print('str[-1] = ', str[-1])

#slicing 2nd to 5th character
print('str[1:5] = ', str[1:5])

#slicing 6th to 2nd last character
print('str[5:-2] = ', str[5:-2])

print('str[-3:-1] =', str[-3:-1])

print(str[1::2])

days = "Mon, Tue, Wed, Thu, Fri, Sat, Sun"
print(days[::5]) # prints M then character at index 0+5 = 5 i.e T then character
# at 5+5 = 10 i.e W & so on....

print(str[::-1])  # slicing backwards over entire range 
print(str[::-2])  # slicing backwards over entire range with a stride of 2 

str =  programiz
str[0] =  p
str[-1] =  z
str[1:5] =  rogr
str[5:-2] =  am
str[-3:-1] = mi
rgai
MTWTFSS
zimargorp
zmrop


In [27]:
f = "abcef"
f = f[:2]+'d'+f[3:]
f

'abdef'

## 5c.2 Strings - Immutable objects?

#How to change or delete a string?

Strings are immutable. This means that elements of a string cannot be changed once they have been assigned. We can simply reassign different strings to the same name.

We cannot delete or remove characters from a string. But deleting the string entirely is possible using the del keyword.

## 5c.3 Concatenation of Strings with strings & numbers

#Concatenation of Two or More Strings

Joining of two or more strings into a single one is called concatenation.

The + operator does this in Python. Simply writing two string literals together also concatenates them.

The * operator can be used to repeat the string for a given number of times.



In [1]:
# Python String Operations
str1 = 'Hello'
str2 ='World!'

# using +
print('str1 + str2 = ', str1 + str2)

# concatenate string and number 
## 1st method : COERCING
string1 = "My age is "
age = 24
print(string1 + str(age) + " years")

## 2nd Method - REPLACEMENT by .format
print("My age is {0} years".format(age))

print("There are {0} days in {1}, {2}, {3}, {4}, {5}, {6}, {7}"
      .format(31,"Jan","Mar","May","Jul","Aug","Oct","Dec"))
### {} - values within curly braces are called replacement fields. 

print("Jan: {2}, Feb: {0}, Mar: {2}, Apr: {1}, May: {2}, Jun: {1}, Jul: {2}, Sep: {1}, Oct: {2}, Nov: {1}, Dec: {2}"
      .format(28, 30, 31))

print()

print("""Jan: {2}
Feb: {0}
Mar: {2}
Apr: {1}
May: {2}
Jun: {1}
Jul: {2}
Sep: {1}
Oct: {2}
Nov: {1}
Dec: {2}""".format(28, 30, 31))

# formatting strings

for i in range(1,13):
    print("No. {0} squared is {1} and cubed is {2}".format(i, i**2 , i**3))
# however this above statement produces o/p which is not perfectly lined up
# hence we use formatting by setting up width in each replacement field 

print()

for i in range(1,13):
    print("No. {0:2} squared is {1:3} and cubed is {2:4}".format(i, i**2 , i**3))
print()

## for left allignment use < symmbol 
for i in range(1,13):
    print("No. {0:2} squared is {1:<3} and cubed is {2:<4}".format(i, i**2 , i**3))
    
print()   

## for center allignment use ^ symbol
for i in range(1,13):
    print("No. {0:2} squared is {1:^3} and cubed is {2:^4}".format(i, i**2 , i**3))

## for decimal values 
print("Pi is approximately = {0:12}".format(22/7))
print("Pi is approximately = {0:12f}".format(22/7))
print("Pi is approximately = {0:12.50f}".format(22/7))
print("Pi is approximately = {0:<52.50f}".format(22/7))
print("Pi is approximately = {0:62.50f}".format(22/7))
print("Pi is approximately = {0:<72.50f}".format(22/7))


#f strings
age = 24
print(f"My age is {age} years")

print(f"Pi is approximately = {22/7:12.50f}")

# using *
print('str1 * 3 =', str1 * 3)

str1 + str2 =  HelloWorld!
My age is 24 years
My age is 24 years
There are 31 days in Jan, Mar, May, Jul, Aug, Oct, Dec
Jan: 31, Feb: 28, Mar: 31, Apr: 30, May: 31, Jun: 30, Jul: 31, Sep: 30, Oct: 31, Nov: 30, Dec: 31

Jan: 31
Feb: 28
Mar: 31
Apr: 30
May: 31
Jun: 30
Jul: 31
Sep: 30
Oct: 31
Nov: 30
Dec: 31
No. 1 squared is 1 and cubed is 1
No. 2 squared is 4 and cubed is 8
No. 3 squared is 9 and cubed is 27
No. 4 squared is 16 and cubed is 64
No. 5 squared is 25 and cubed is 125
No. 6 squared is 36 and cubed is 216
No. 7 squared is 49 and cubed is 343
No. 8 squared is 64 and cubed is 512
No. 9 squared is 81 and cubed is 729
No. 10 squared is 100 and cubed is 1000
No. 11 squared is 121 and cubed is 1331
No. 12 squared is 144 and cubed is 1728

No.  1 squared is   1 and cubed is    1
No.  2 squared is   4 and cubed is    8
No.  3 squared is   9 and cubed is   27
No.  4 squared is  16 and cubed is   64
No.  5 squared is  25 and cubed is  125
No.  6 squared is  36 and cubed is  216
No.  7 s

Writing two string literals together also concatenates them like + operator.

If we want to concatenate strings in different lines, we can use parentheses.

In [2]:
s = 'Hello'' ''World'
print(s) 

s = ('Hello'
     ' '
     'World')
print(s)

Hello World
Hello World


In [12]:
# Iterating through a string
count = 0
for letter in 'Hello World':
    if(letter == 'l'):
        count += 1
print(count,'letters found')

3 letters found


## 5c.4 in & not in - Membership Operators

In [3]:
'a' in 'program'
# True

True

In [15]:
'at' not in 'battle'
# False

False

Built-in functions to Work with Python
Various built-in functions that work with sequence work with strings as well.

Some of the commonly used ones are enumerate() and len(). The enumerate() function returns an enumerate object. It contains the index and value of all the items in the string as pairs. This can be useful for iteration.

Similarly, len() returns the length (number of characters) of the string.

In [16]:
str = 'cold'

# enumerate()
list_enumerate = list(enumerate(str))
print('list(enumerate(str) = ', list_enumerate)

#character count
print('len(str) = ', len(str))

list(enumerate(str) =  [(0, 'c'), (1, 'o'), (2, 'l'), (3, 'd')]
len(str) =  4


In [7]:
string = "enumerate"
for i,j in enumerate(string):
    print("The value for index {0} is {1}".format(i,j))

The value for index 0 is e
The value for index 1 is n
The value for index 2 is u
The value for index 3 is m
The value for index 4 is e
The value for index 5 is r
The value for index 6 is a
The value for index 7 is t
The value for index 8 is e


## 5c.5 Methods in strings

### 5c.5.1 str.count(3)

In [49]:
# a.count(substring,[start,end]) :Counts the occurrences of a substring with
# optional start and end parameters.

a = 'abcabcabcabb'
a.count('a',3,10) # index starts from 0 and if the end in at index i then 
                  # it counts upto index (i-1)


3

In [50]:
a.count('b',3) # counts from index 3 to last index 

4

In [1]:
# Example of method count() : ANAGRAMS

# Two words are called anagrams if they have the exact same letters but in a 
# different order. For example, 'night' and 'thing' are anagrams.

# Can you write a code to find out if two strings are anagrams or no?


#take input here
s1 = input()
s2 = input()

#code here to check if they are anagrams or no

def anagram(s1,s2):
    #if length doesnt match then they are definitely not anagrams
    if len(s1)!=len(s2):
        return False
    
    #we will check count of each character one by one
    for i in range(len(s1)):
        if s1.count(s1[i]) != s2.count(s1[i]):
            return False
   #if we come out of the for loop means we didnt exit the function in loop
   #remember we exit the function when we return
   #this means there was no occurance where s1.count(s1[i]) != s2.count(s1[i]) was True
   #this means the strings are anagrams
    return True

print(anagram(s1,s2))


amanaa
ammana
False


### 5c.5.2 str.find(3)

In [56]:
# s.find(substring, [start, end]) Returns the index of the first occurrence of 
# a substring or returns -1 if the substring is not found

In [57]:
quote = 'Let it be, let it be, let it be'

# first occurance of 'let it'(case sensitive)
result = quote.find('let it')
print("Substring 'let it':", result)

# find returns -1 if substring not found
result = quote.find('small')
print("Substring 'small ':", result)

# How to use find()
if (quote.find('be,') != -1):
    print("Contains substring 'be,'")
else:
    print("Doesn't contain substring")

Substring 'let it': 11
Substring 'small ': -1
Contains substring 'be,'


In [58]:
quote = 'Do small things with great love'

# Substring is searched in 'hings with great love'
print(quote.find('small things', 10))

# Substring is searched in ' small things with great love' 
print(quote.find('small things', 2))

# Substring is searched in 'hings with great lov'
print(quote.find('o small ', 10, -1))

# Substring is searched in 'll things with'
print(quote.find('things ', 6, 20))

-1
3
-1
9


### 5c.5.3 str.rfind(3)

rfind() Parameters

rfind() method takes a maximum of three parameters:

sub - It's the substring to be searched in the str string.
start and end (optional) - substring is searched within str[start:end]

Return Value from rfind()

rfind() method returns an integer value.

If substring exists inside the string, it returns the highest index where substring is found.
If substring doesn't exist inside the string, it returns -1.
How find() and rfind() works in Python?

In [59]:
quote = 'Let it be, let it be, let it be'

result = quote.rfind('let it')
print("Substring 'let it':", result)

result = quote.rfind('small')
print("Substring 'small ':", result)

result = quote.rfind('be,')
if  (result != -1):
  print("Highest index where 'be,' occurs:", result)
else:
  print("Doesn't contain substring")

Substring 'let it': 22
Substring 'small ': -1
Highest index where 'be,' occurs: 18


In [60]:
quote = 'Do small things with great love'

# Substring is searched in 'hings with great love'
print(quote.rfind('things', 10))

# Substring is searched in ' small things with great love' 
print(quote.rfind('t', 2))

# Substring is searched in 'hings with great lov'
print(quote.rfind('o small ', 10, -1))

# Substring is searched in 'll things with'
print(quote.rfind('th', 6, 20))

-1
25
-1
18


In [70]:
sentence = 'Python programming is fun is fun is fun'

result = sentence.index('is fun') # returns the 1st index ecountered 
print("Substring 'is fun':", result)

result = sentence.rindex('is fun') # returns the last index encountered.
print("Substring 'is fun':", result)

result = sentence.index('java')
print("Substring 'is fun':", result)

Substring 'is fun': 19
Substring 'is fun': 33


ValueError: substring not found

### 5c.5.4 str.endswith(3)

endswith() Parameters
The endswith() takes three parameters:

suffix - String or tuple of suffixes to be checked
start (optional) - Beginning position where suffix is to be checked within the string.
end (optional) - Ending position where suffix is to be checked within the string.
Return Value from endswith()
The endswith() method returns a boolean.

It returns True if strings ends with the specified suffix.
It returns False if string doesn't end with the specified suffix.

In [71]:
text = "Python is easy to learn."

result = text.endswith('to learn')
# returns False
print(result)

result = text.endswith('to learn.')
# returns True
print(result)

result = text.endswith('Python is easy to learn.')
# returns True
print(result)

False
True
True


In [72]:
text = "Python programming is easy to learn."

# start parameter: 7
# "programming is easy to learn." string is searched
result = text.endswith('learn.', 7)
print(result)

# Both start and end is provided
# start: 7, end: 26
# "programming is easy" string is searched

result = text.endswith('is', 7, 26)
# Returns False
print(result)

result = text.endswith('easy', 7, 26)
# returns True
print(result)

True
False
True


Passing Tuple to endswith()

It's possible to pass a tuple suffixes to the endswith() method in Python.

If the string ends with any item of the tuple, endswith() returns True. If not, it returns False



In [73]:
text = "programming is easy"
result = text.endswith(('programming', 'python'))

# prints False
print(result)

result = text.endswith(('python', 'easy', 'java'))

#prints True
print(result)

# With start and end parameter
# 'programming is' string is checked
result = text.endswith(('is', 'an'), 0, 14)

# prints True
print(result)

False
True
True


### 5c.5.5 str.startswith(3)

startswith() Parameters
startswith() method takes a maximum of three parameters:

prefix - String or tuple of strings to be checked
start (optional) - Beginning position where prefix is to be checked within the string.
end (optional) - Ending position where prefix is to be checked within the string.
Return Value from startswith()
startswith() method returns a boolean.

It returns True if the string starts with the specified prefix.
It returns False if the string doesn't start with the specified prefix.

In [75]:
text = "Python is easy to learn."

result = text.startswith('is easy')
# returns False
print(result)

result = text.startswith('Python is ')
# returns True
print(result)

result = text.startswith('Python is easy to learn.')
# returns True
print(result)

False
True
True


In [76]:
text = "Python programming is easy."

# start parameter: 7
# 'programming is easy.' string is searched
result = text.startswith('programming is', 7)
print(result)

# start: 7, end: 18
# 'programming' string is searched
result = text.startswith('programming is', 7, 18)
print(result)

result = text.startswith('program', 7, 18)
print(result)

True
False
True


In [77]:
text = "programming is easy"
result = text.startswith(('python', 'programming'))

# prints True
print(result)

result = text.startswith(('is', 'easy', 'java'))

# prints False
print(result)

# With start and end parameter
# 'is easy' string is checked
result = text.startswith(('programming', 'easy'), 12, 19)

# prints False
print(result)

True
False
False


### 5c.5.6 str.split(2)



split() Parameters
split() method takes a maximum of 2 parameters:

separator (optional)- It is a delimiter. The string splits at the specified separator.
If the separator is not specified, any whitespace (space, newline etc.) string is a separator.
maxsplit (optional) - The maxsplit defines the maximum number of splits.
The default value of maxsplit is -1, meaning, no limit on the number of splits.


Return Value from split()
split() breaks the string at the separator and returns a list of strings.The split() method breaks up a string at the specified separator and returns a list of strings.



In [17]:
text= 'Love thy neighbor'

# splits at space
print(text.split())

grocery = 'Milk, Chicken, Bread'

# splits at ','
print(grocery.split(', '))

# Splitting at ':'
print(grocery.split(':'))

['Love', 'thy', 'neighbor']
['Milk', 'Chicken', 'Bread']
['Milk, Chicken, Bread']


In [79]:
grocery = 'Milk, Chicken, Bread, Butter'

# maxsplit: 2
print(grocery.split(', ', 2))

# maxsplit: 1
print(grocery.split(', ', 1))

# maxsplit: 5
print(grocery.split(', ', 5))

# maxsplit: 0
print(grocery.split(', ', 0))

['Milk', 'Chicken', 'Bread, Butter']
['Milk', 'Chicken, Bread, Butter']
['Milk', 'Chicken', 'Bread', 'Butter']
['Milk, Chicken, Bread, Butter']


### 5c.5.7 str.rsplit(2)

rsplit() Parameters
rsplit() method takes maximum of 2 parameters:

separator (optional)- The is a delimiter. rsplit() method splits string starting from the right at the specified separator.
If the separator is not specified, any whitespace (space, newline etc.) string is a separator.
maxsplit (optional) - The maxsplit defines the maximum number of splits.
The default value of maxsplit is -1, meaning, no limit on the number of splits.


Return Value from rsplit()
rsplit() breaks the string at the separator starting from the right and returns a list of strings.

In [80]:
text= 'Love thy neighbor'

# splits at space
print(text.rsplit())

grocery = 'Milk, Chicken, Bread'

# splits at ','
print(grocery.rsplit(', '))

# Splitting at ':'
print(grocery.rsplit(':'))

['Love', 'thy', 'neighbor']
['Milk', 'Chicken', 'Bread']
['Milk, Chicken, Bread']


In [81]:
grocery = 'Milk, Chicken, Bread, Butter'

# maxsplit: 2
print(grocery.rsplit(', ', 2))

# maxsplit: 1
print(grocery.rsplit(', ', 1))

# maxsplit: 5
print(grocery.rsplit(', ', 5))

# maxsplit: 0
print(grocery.rsplit(', ', 0))

['Milk, Chicken', 'Bread', 'Butter']
['Milk, Chicken, Bread', 'Butter']
['Milk', 'Chicken', 'Bread', 'Butter']
['Milk, Chicken, Bread, Butter']


### 5c.5.8 str.splitlines(1)

The syntax of splitlines() is:

str.splitlines([keepends])

splitlines() Parameters
splitlines() takes maximum of 1 parameter.

keepends (optional) - If keepends is provided and True, line breaks are also included in items of the list.

By default, the line breaks are not included.

Return Value from splitlines()
splitlines() returns a list of lines in the string.

If there are not line break characters, it returns a list with a single item (a single line).

splitlines() splits on the following line boundaries:

Representation	Description
\n	            Line Feed
\r	            Carriage Return
\r\n	        Carriage Return + Line Feed
\v or \x0b	    Line Tabulation
\f or \x0c	    Form Feed
\x1c	        File Separator
\x1d	        Group Separator
\x1e	        Record Separator
\x85	        Next Line (C1 Control Code)
\u2028	        Line Separator
\u2029	        Paragraph Separator

In [82]:
grocery = 'Milk\nChicken\r\nBread\rButter'

print(grocery.splitlines())
print(grocery.splitlines(True))

grocery = 'Milk Chicken Bread Butter'
print(grocery.splitlines())

['Milk', 'Chicken', 'Bread', 'Butter']
['Milk\n', 'Chicken\r\n', 'Bread\r', 'Butter']
['Milk Chicken Bread Butter']


### 5c.5.9 str.strip(1)

Python String strip()
The strip() method returns a copy of the string by removing both the leading and the trailing characters (based on the string argument passed).

The strip() method removes characters from both left and right based on the argument (a string specifying the set of characters to be removed).

The syntax of the strip() method is:

string.strip([chars])

strip() Parameters
chars (optional) - a string specifying the set of characters to be removed from the left and right part of the string.
If the chars argument is not provided, all leading and trailing whitespaces are removed from the string.

Return Value from the strip() method
strip() returns a copy of the string with both leading and trailing characters stripped.

Working of the strip() method
When the character of the string in the left mismatches with all the characters in the chars argument, it stops removing the leading characters.
Similarly, when the character of the string in the right mismatches with all the characters in the chars argument, it stops removing the trailing characters.


In [22]:
string = '  xoxo love xoxo   '

# Leading and trailing whitespaces are removed
print(string.strip())

# All <whitespace>,x,o,e characters in the left
# and right of string are removed
print(string.strip(' xoe'))

# Argument doesn't contain space
# No characters are removed.
print(string.strip('stx'))

string = 'android is awesome'
print(string.strip('an'))

st = '*********what is it?*****'
print(st.strip('*'))

xoxo love xoxo
lov
  xoxo love xoxo   
droid is awesome
what is it?


Here, we can see that the first expression string.strip() without any arguments removed the whitespaces from the left and right of string.

string.strip(' xoe') removed all whitespace,x, o, and e that lead or trailed the string.

Since string has whitespace at the beginning and end, the expression string.strip('stx') does not change the string. x is not removed since it is at the middle of the string (whitespaces lead and trail the string)

string.strip('an') removed an leading the string.

### 5c.5.10 str.rstrip(1)

Python String rstrip()
The rstrip() method returns a copy of the string with trailing characters removed (based on the string argument passed).

The rstrip() removes characters from the right based on the argument (a string specifying the set of characters to be removed).

The syntax of rstrip() is:

string.rstrip([chars])

rstrip() Parameters
chars (optional) - a string specifying the set of characters to be removed.
If chars argument is not provided, all whitespaces on the right are removed from the string.

Return Value from rstrip() 
The rstrip() returns a copy of the string with trailing characters stripped.

All combinations of characters in chars argument are removed from the right of the string until first mismatch.



In [25]:
random_string = 'this is good   '

# Trailing whitepsace are removed
print(random_string.rstrip())

# Argument doesn't contain 'd', hence No characters are removed.
print(random_string.rstrip('si oo'))

print(random_string.rstrip('sid oo'))

website = 'www.programiz.com/'
print(website.rstrip('m/.'))

st = 'hot weather!!###$@#::::&&'
print(st.rstrip('$!#@&:'))
print(st.rstrip('$!#@:')) # since the string ends with '&' , without mentioning
#it doesnot yield any result 

this is good
this is good
this is g
www.programiz.co
hot weather
hot weather!!###$@#::::&&


### 5c.5.11 str.lstrip(1)

Python String lstrip()
The lstrip() method returns a copy of the string with leading characters removed (based on the string argument passed).

The lstrip() removes characters from the left based on the argument (a string specifying the set of characters to be removed).

The syntax of lstrip() is:

string.lstrip([chars])

lstrip() Parameters
chars (optional) - a string specifying the set of characters to be removed.
If chars argument is not provided, all leading whitespaces are removed from the string.

Return Value from lstrip() 
lstrip() returns a copy of the string with leading characters stripped.

All combinations of characters in the chars argument are removed from the left of the string until the first mismatch

In [85]:
random_string = '   this is good '

# Leading whitepsace are removed
print(random_string.lstrip())

# Argument doesn't contain space
# No characters are removed.
print(random_string.lstrip('sti'))

print(random_string.lstrip('s ti'))

website = 'https://www.programiz.com/'
print(website.lstrip('htps:/.'))

this is good 
   this is good 
his is good 
www.programiz.com/


### 5c.5.12 str.join(iterable)

Python String join()
The join() string method returns a string by joining all the elements of an iterable, separated by a string separator.

The join() method provides a flexible way to create strings from iterable objects. It joins each element of an iterable (such as list, string, and tuple) by a string separator (the string on which the join() method is called) and returns the concatenated string.

The syntax of the join() method is:

string.join(iterable)

Parameters for the join() method
The join() method takes an iterable (objects capable of returning its members one at a time) as its parameter.

Some of the example of iterables are:

Native data types - List, Tuple, String, Dictionary and Set.
File objects and objects you define with an __iter__() or __getitem()__ method.

Return Value from join() method
The join() method returns a string created by joining the elements of an iterable by string separator.


If the iterable contains any non-string values, it raises a TypeError exception.



In [86]:
# .join() with lists
numList = ['1', '2', '3', '4']
separator = ', '
print(separator.join(numList))

# .join() with tuples
numTuple = ('1', '2', '3', '4')
print(separator.join(numTuple))

s1 = 'abc'
s2 = '123'

# each element of s2 is separated by s1
# '1'+ 'abc'+ '2'+ 'abc'+ '3'
print('s1.join(s2):', s1.join(s2))

# each element of s1 is separated by s2
# 'a'+ '123'+ 'b'+ '123'+ 'b'
print('s2.join(s1):', s2.join(s1))

1, 2, 3, 4
1, 2, 3, 4
s1.join(s2): 1abc2abc3
s2.join(s1): a123b123c


In [87]:
# .join() with sets
test = {'2', '1', '3'}
s = ', '
print(s.join(test))

test = {'Python', 'Java', 'Ruby'}
s = '->->'
print(s.join(test))

3, 1, 2
Java->->Python->->Ruby


In [90]:
# .join() with dictionaries
test = {'mat': 1, 'that': 2}
s = '->'

# joins the keys only
print(s.join(test))

test = {1: 'mat', 2: 'that'}
s = ', '

# this gives error since key isn't string and the join() applies to the key
# of the ductionary 

print(s.join(test))

mat->that


TypeError: sequence item 0: expected str instance, int found

The join() method tries to join the keys (not values) of the dictionary with the string separator.

Note: If the key of the string is not a string, it raises a TypeError exception.

### 5c.5.13 str.partition(1)

Python String partition()

The partition() method splits the string at the first occurrence of the argument string and returns a tuple containing the part the before separator, argument string and the part after the separator.

The syntax of partition() is:

string.partition(separator)

partition() Parameters()
The partition() method takes a string parameter separator that separates the string at the first occurrence of it.

Return Value from partition()
The partition method returns a 3-tuple containing:

the part before the separator, separator parameter, and the part after the separator if the separator parameter is found in the string
the string itself and two empty strings if the separator parameter is not found

In [91]:
string = "Python is fun"

# 'is' separator is found
print(string.partition('is '))

# 'not' separator is not found
print(string.partition('not '))

string = "Python is fun, isn't it"

# splits at first occurence of 'is'
print(string.partition('is'))

('Python ', 'is ', 'fun')
('Python is fun', '', '')
('Python ', 'is', " fun, isn't it")


### 5c.5.14 str.rpartition(1)

Python String rpartition()
The rpartition() splits the string at the last occurrence of the argument string and returns a tuple containing the part the before separator, argument string and the part after the separator.

The syntax of rpartition() is:

string.rpartition(separator)

rpartition() Parameters()
rpartition() method takes a string parameter separator that separates the string at the last occurrence of it.

Return Value from rpartition()
rpartition() method returns a 3-tuple containing:

the part before the separator, separator parameter, and the part after the separator if the separator parameter is found in the string
two empty strings, followed by the string itself if the separator parameter is not found


In [94]:

string = "Python is fun"

# 'is' separator is found
print(string.rpartition('is '))

# 'not' separator is not found
print(string.rpartition('not '))

string = "Python is fun, isn't it"

# splits at last occurence of 'is'
print(string.rpartition('is'))

('Python ', 'is ', 'fun')
('', '', 'Python is fun')
('Python is fun, ', 'is', "n't it")


### 5c.5.15 str.replace(3)

Python String replace()

The replace() method returns a copy of the string where all occurrences of a substring is replaced with another substring.

The syntax of replace() is:

str.replace(old, new [, count]) 

replace() parameters
The replace() method can take maximum of 3 parameters:

old - old substring you want to replace
new - new substring which will replace the old substring
count (optional) - the number of times you want to replace the old substring with the new substring
Note: If count is not specified, the replace() method replaces all occurrences of the old substring with the new substring.

Return Value from replace()
The replace() method returns a copy of the string where the old substring is replaced with the new substring. The original string is unchanged.

If the old substring is not found, it returns the copy of the original string.

In [6]:
song = 'cold, cold heart'

# replacing 'cold' with 'hurt'
print(song.replace('cold', 'hurt'))

song = 'Let it be, let it be, let it be, let it be'

# replacing only two occurences of 'let'
print(song.replace('let', "don't let",2))  # does not replace 1st occurrence of 
# "Let it" because it is case specific 

hurt, hurt heart
Let it be, don't let it be, don't let it be, let it be


In [2]:
song = 'cold, cold heart'
replaced_song = song.replace('o', 'e')

# The original string is unchanged
print('Original string:', song)

print('Replaced string:', replaced_song)

song = 'let it be, let it be, let it be'

# maximum of 0 substring is replaced
# returns copy of the original string
print(song.replace('let', 'so', 0))

Original string: cold, cold heart
Replaced string: celd, celd heart
let it be, let it be, let it be


### 5c.5.16 str.rjust(2)

Python String rjust()
The string rjust() method returns a right-justified string of a given minimum width.

The syntax of rjust() method is:

string.rjust(width[, fillchar])
Here, fillchar is an optional parameter.

String rjust() Parameters
The rjust() method takes two parameters:

width - width of the given string. If width is less than or equal to the length of the string, original string is returned.
fillchar (Optional) - character to fill the remaining space of the width

Return value from String rjust()

The rjust() method returns the right-justified string within the given minimum width.

If fillchar is defined, it fills the remaining space with the defined character.

In [97]:
# example string
string = 'cat'
width = 5

# print right justified string
print(string.rjust(width))

  cat


In [98]:
# example string
string = 'cat'
width = 5
fillchar = '*'

# print right justified string
print(string.rjust(width, fillchar))

**cat


Here, the string cat is aligned to the right and the remaining two spaces on its left are filled with the fillchar *.

Note: If you want to right justify the string, use ljust(). You can also use format() for formatting of the strings.

### 5c.5.17 str.ljust(2)

Python String ljust()
The string ljust() method returns a left-justified string of a given minimum width.

The syntax of ljust() method is:

string.ljust(width[, fillchar])
Here, fillchar is an optional parameter.

String ljust() Parameters
ljust() method takes two parameters:

width - width of the given string. If width is less than or equal to the length of the string, the original string is returned.
fillchar (Optional) - character to fill the remaining space of the width

Return value from String ljust()
The ljust() method returns the left-justified string within the given minimum width.

If fillchar is defined, it also fills the remaining space with the defined character.



In [99]:
# example string
string = 'cat'
width = 5

# print left justified string
print(string.ljust(width))

cat  


Here, the minimum width defined is 5. So, the resultant string is of minimum length 5.

And, the string cat is aligned to the left which makes leaves two spaces on the right of the word.

In [100]:
# example string
string = 'cat'
width = 5
fillchar = '*'

# print left justified string
print(string.ljust(width, fillchar))

cat**


Here, the string cat is aligned to the left, and the remaining two spaces on the right is filled with the character *.

Note: If you want to right justify the string, use rjust(). You can also use format() method for the formatting of strings.

### 5c.5.18 str.upper(0)

Python String upper()
The string upper() method converts all lowercase characters in a string into uppercase characters and returns it.

The syntax of upper() method is:

string.upper()
String upper() Parameters()
upper() method doesn't take any parameters.

Return value from String upper()
upper() method returns the uppercased string from the given string. It converts all lowercase characters to uppercase.

If no lowercase characters exist, it returns the original string.



In [101]:
# example string
string = "this should be uppercase!"
print(string.upper())

# string with numbers
# all alphabets whould be lowercase
string = "Th!s Sh0uLd B3 uPp3rCas3!"
print(string.upper())

THIS SHOULD BE UPPERCASE!
TH!S SH0ULD B3 UPP3RCAS3!


In [102]:
# first string
firstString = "python is awesome!"

# second string
secondString = "PyThOn Is AwEsOmE!"

if(firstString.upper() == secondString.upper()):
    print("The strings are same.")
else:
    print("The strings are not same.")

The strings are same.


Note: If you want to convert to lowercase string, use lower(). You can also use swapcase() to swap between lowercase to uppercase.

### 5c.5.19 str.lower(0)

Python String lower()
The string lower() method converts all uppercase characters in a string into lowercase characters and returns it.

The syntax of lower() method is:

string.lower()
String lower() Parameters()
lower() method doesn't take any parameters.

Return value from String lower()
lower() method returns the lowercased string from the given string. It converts all uppercase characters to lowercase.

If no uppercase characters exist, it returns the original string.

In [103]:
# example string
string = "THIS SHOULD BE LOWERCASE!"
print(string.lower())

# string with numbers
# all alphabets whould be lowercase
string = "Th!s Sh0uLd B3 L0w3rCas3!"
print(string.lower())

this should be lowercase!
th!s sh0uld b3 l0w3rcas3!


In [104]:
# first string
firstString = "PYTHON IS AWESOME!"

# second string
secondString = "PyThOn Is AwEsOmE!"

if(firstString.lower() == secondString.lower()):
    print("The strings are same.")
else:
    print("The strings are not same.")

The strings are same.


### 5c.5.20 str.swapcase(0)

Python String swapcase()
The string swapcase() method converts all uppercase characters to lowercase and all lowercase characters to uppercase characters of the given string, and returns it.

The format of swapcase() method is:

string.swapcase()
Note: Not necessarily, string.swapcase().swapcase() == string

String swapcase() Parameters()
swapcase() method doesn't take any parameters.

Return value from String swapcase()
swapcase() method returns the string where all uppercase characters are converted to lowercase, and lowercase characters are converted to uppercase.



In [105]:
# example string
string = "THIS SHOULD ALL BE LOWERCASE."
print(string.swapcase())

string = "this should all be uppercase."
print(string.swapcase())

string = "ThIs ShOuLd Be MiXeD cAsEd."
print(string.swapcase())

this should all be lowercase.
THIS SHOULD ALL BE UPPERCASE.
tHiS sHoUlD bE mIxEd CaSeD.


### 5c.5.21 str.title(0)

Python String title()
The title() method returns a string with first letter of each word capitalized; a title cased string.

The syntax of title() is:

str.title()
title() Parameters
title() method doesn't take any parameters.

Return Value from title()
title() method returns a title cased version of the string. Meaning, the first character of each word is capitalized (if the first character is a letter).



In [106]:
text = 'My favorite number is 25.'
print(text.title())

text = '234 k3l2 *43 fun'
print(text.title())

My Favorite Number Is 25.
234 K3L2 *43 Fun


In [107]:
text = "He's an engineer, isn't he?"
print(text.title())

He'S An Engineer, Isn'T He?


In [108]:
import re  #Using Regex to Title Case String

def titlecase(s):
    return re.sub(r"[A-Za-z]+('[A-Za-z]+)?",
     lambda mo: mo.group(0)[0].upper() +
     mo.group(0)[1:].lower(),
     s)

text = "He's an engineer, isn't he?"
print(titlecase(text))

He's An Engineer, Isn't He?


### 5c.5.22 str.casefold(0)

Python String casefold()
The casefold() method is an aggressive lower() method which converts strings to case folded strings for caseless matching.

The casefold() method removes all case distinctions present in a string. It is used for caseless matching, i.e. ignores cases when comparing.

For example, the German lowercase letter ß is equivalent to ss. However, since ß is already lowercase, the lower() method does nothing to it. But, casefold() converts it to ss.

The syntax of casefold() is:

string.casefold()

Parameters for casefold()
The casefold() method doesn't take any parameters.

Return value from casefold()
The casefold() method returns the case folded string.



In [109]:
string = "PYTHON IS AWESOME"

# print lowercase string
print("Lowercase string:", string.casefold())

Lowercase string: python is awesome


In [110]:
firstString = "der Fluß"
secondString = "der Fluss"

# ß is equivalent to ss
if firstString.casefold() == secondString.casefold():
    print('The strings are equal.')
else:
    print('The strings are not equal.')

The strings are equal.


### 5c.5.23 str.capitalize(0)

Python String capitalize()
In Python, the capitalize() method converts first character of a string to uppercase letter and lowercases all other characters, if any.

The syntax of capitalize() is:

string.capitalize()
capitalize() Parameter
The capitalize()function doesn't take any parameter.

Return Value from capitalize()
The capitalize() function returns a string with the first letter capitalized and all other characters lowercased. It doesn't modify the original string.



In [111]:
string = "python is AWesome."

capitalized_string = string.capitalize()

print('Old String: ', string)
print('Capitalized String:', capitalized_string)

Old String:  python is AWesome.
Capitalized String: Python is awesome.


In [112]:
string = "+ is an operator."  # Non-alphabetic First Character

new_string = string.capitalize()

print('Old String:', string)
print('New String:', new_string)

Old String: + is an operator.
New String: + is an operator.


### 5c.5.24 str.zfill(1)

Python String zfill()
The zfill() method returns a copy of the string with '0' characters padded to the left.

The syntax of zfill() in Python is:

str.zfill(width)
zfill() Parameter
zfill() takes a single character width.

The width specifies the length of the returned string from zfill() with 0 digits filled to the left.

Return Value from zfill()
zfill() returns a copy of the string with 0 filled to the left. The length of the returned string depends on the width provided.

Suppose, the initial length of the string is 10. And, the width is specified 15. In this case, zfill() returns a copy of the string with five '0' digits filled to the left.
Suppose, the initial length of the string is 10. And, the width is specified 8. In this case, zfill() doesn't fill '0' digits to the left and returns a copy of the original string. The length of the returned string in this case will be 10.

In [113]:
text = "program is fun"
print(text.zfill(15))
print(text.zfill(20))
print(text.zfill(10))

0program is fun
000000program is fun
program is fun


In [115]:
# How zfill() works with Sign Prefix?

number = "-290" 
print(number.zfill(8))

number = "+290"
print(number.zfill(8))

text = "--random+text"
print(text.zfill(20))

-0000290
+0000290
-0000000-random+text


### 5c.5.25 str.center(2)

Python String center()
The center() method returns a string which is padded with the specified character.

The syntax of center() method is:

string.center(width[, fillchar])

center() Parameters
The center() method takes two arguments:

width - length of the string with padded characters
fillchar (optional) - padding character
The fillchar argument is optional. If it's not provided, space is taken as default argument.

Return Value from center()
The center() method returns a string padded with specified fillchar. It doesn't modify the original string.



In [116]:
string = "Python is awesome"

new_string = string.center(24)

print("Centered String: ", new_string)

Centered String:     Python is awesome    


In [117]:
string = "Python is awesome"

new_string = string.center(24, '*')

print("Centered String: ", new_string)

Centered String:  ***Python is awesome****


The string format() method formats the given string into a nicer output in Python.

The syntax of the format() method is:

template.format(p0, p1, ..., k0=v0, k1=v1, ...)
Here, p0, p1,... are positional arguments and, k0, k1,... are keyword arguments with values v0, v1,... respectively.

And, template is a mixture of format codes with placeholders for the arguments.

String format() Parameters
format() method takes any number of parameters. But, is divided into two types of parameters:

Positional parameters - list of parameters that can be accessed with index of parameter inside curly braces {index}
Keyword parameters - list of parameters of type key=value, that can be accessed with key of parameter inside curly braces {key}
Return value from String format()
The format() method returns the formatted string.



In [ ]:
How String format() works?

The format() reads the type of arguments passed to it and formats it according to the format codes defined in the string.

For positional arguments

Positional arguments
Here, Argument 0 is a string "Adam" and Argument 1 is a floating number 230.2346.

Note: Argument list starts from 0 in Python.

The string "Hello {0}, your balance is {1:9.3f}" is the template string. This contains the format codes for formatting.

The curly braces are just placeholders for the arguments to be placed. In the above example, {0} is placeholder for "Adam" and {1:9.3f} is placeholder for 230.2346.

Since the template string references format() arguments as {0} and {1}, the arguments are positional arguments. They both can also be referenced without the numbers as {} and Python internally converts them to numbers.

Internally,

Since "Adam" is the 0th argument, it is placed in place of {0}. Since, {0} doesn't contain any other format codes, it doesn't perform any other operations.
However, it is not the case for 1st argument 230.2346. Here, {1:9.3f} places 230.2346 in its place and performs the operation 9.3f.
f specifies the format is dealing with a float number. If not correctly specified, it will give out an error.
The part before the "." (9) specifies the minimum width/padding the number (230.2346) can take. In this case, 230.2346 is allotted a minimum of 9 places including the ".".
If no alignment option is specified, it is aligned to the right of the remaining spaces. (For strings, it is aligned to the left.)
The part after the "." (3) truncates the decimal part (2346) upto the given number. In this case, 2346 is truncated after 3 places.
Remaining numbers (46) is rounded off outputting 235.

For keyword arguments
Keyword argument


We've used the same example from above to show the difference between keyword and positional arguments.

Here, instead of just the parameters, we've used a key-value for the parameters. Namely, name="Adam" and blc=230.2346.

Since these parameters are referenced by their keys as {name} and {blc:9.3f}, they are known as keyword or named arguments.

Internally,

The placeholder {name} is replaced by the value of name - "Adam". Since it doesn't contain any other format codes, "Adam" is placed.
For the argument blc=230.2346, the placeholder {blc:9.3f} is replaced by the value 230.2346. But before replacing it, like previous example, it performs 9.3f operation on it.
This outputs   230.235. The decimal part is truncated after 3 places and remaining digits are rounded off. Likewise, the total width is assigned 9 leaving two spaces to the left.

Basic formatting with format()
The format() method allows the use of simple placeholders for formatting.

In [118]:
# default arguments
print("Hello {}, your balance is {}.".format("Adam", 230.2346))

# positional arguments
print("Hello {0}, your balance is {1}.".format("Adam", 230.2346))

# keyword arguments
print("Hello {name}, your balance is {blc}.".format(name="Adam", blc=230.2346))

# mixed arguments
print("Hello {0}, your balance is {blc}.".format("Adam", blc=230.2346))

Hello Adam, your balance is 230.2346.
Hello Adam, your balance is 230.2346.
Hello Adam, your balance is 230.2346.
Hello Adam, your balance is 230.2346.


Note: In case of mixed arguments, keyword arguments has to always follow positional arguments.

In [ ]:
Numbers formatting with format()
You can format numbers using the format specifier given below:

Number Formatting Types
Type	Meaning
d	Decimal integer
c	Corresponding Unicode character
b	Binary format
o	Octal format
x	Hexadecimal format (lower case)
X	Hexadecimal format (upper case)
n	Same as 'd'. Except it uses current locale setting for number separator
e	Exponential notation. (lowercase e)
E	Exponential notation (uppercase E)
f	Displays fixed point number (Default: 6)
F	Same as 'f'. Except displays 'inf' as 'INF' and 'nan' as 'NAN'
g	General format. Rounds number to p significant digits. (Default precision: 6)
G	Same as 'g'. Except switches to 'E' if the number is large.
%	Percentage. Multiples by 100 and puts % at the end.

In [119]:
# integer arguments
print("The number is:{:d}".format(123))

# float arguments
print("The float number is:{:f}".format(123.4567898))

# octal, binary and hexadecimal format
print("bin: {0:b}, oct: {0:o}, hex: {0:x}".format(12))

The number is:123
The float number is:123.456790
bin: 1100, oct: 14, hex: c


In [120]:
# integer numbers with minimum width
print("{:5d}".format(12))

# width doesn't work for numbers longer than padding
print("{:2d}".format(1234))

# padding for float numbers
print("{:8.3f}".format(12.2346))

# integer numbers with minimum width filled with zeros
print("{:05d}".format(12))

# padding for float numbers filled with zeros
print("{:08.3f}".format(12.2346))

   12
1234
  12.235
00012
0012.235



Here,

in the first statement, {:5d} takes an integer argument and assigns a minimum width of 5. Since, no alignment is specified, it is aligned to the right.

In the second statement, you can see the width (2) is less than the number (1234), so it doesn't take any space to the left but also doesn't truncate the number. 

Unlike integers, floats has both integer and decimal parts. And, the mininum width defined to the number is for both parts as a whole including ".".

In the third statement, {:8.3f} truncates the decimal part into 3 places rounding off the last 2 digits. And, the number, now 12.235, takes a width of 8 as a whole leaving 2 places to the left.

If you want to fill the remaining places with zero, placing a zero before the format specifier does this. It works both for integers and floats: {:05d} and {:08.3f}.


In [121]:
# show the + sign
print("{:+f} {:+f}".format(12.23, -12.23))

# show the - sign only
print("{:-f} {:-f}".format(12.23, -12.23))

# show space for + sign
print("{: f} {: f}".format(12.23, -12.23))

+12.230000 -12.230000
12.230000 -12.230000
 12.230000 -12.230000


Number formatting with alignment
The operators <, ^, > and = are used for alignment when assigned a certain width to the numbers.

Number formatting with alignment
Type	Meaning
<	Left aligned to the remaining space
^	Center aligned to the remaining space, > Right aligned to the remaining space
=	Forces the signed (+) (-) to the leftmost position

In [122]:
# integer numbers with right alignment
print("{:5d}".format(12))

# float numbers with center alignment
print("{:^10.3f}".format(12.2346))

# integer left alignment filled with zeros
print("{:<05d}".format(12))

# float numbers with center alignment
print("{:=8.3f}".format(-12.2346))

   12
  12.235  
12000
- 12.235


Note: Left alignment filled with zeros for integer numbers can cause problems as the 3rd example which returns 12000, rather than 12.

String formatting with format()

As numbers, string can be formatted in a similar way with format()

In [123]:
# string padding with left alignment
print("{:5}".format("cat"))

# string padding with right alignment
print("{:>5}".format("cat"))

# string padding with center alignment
print("{:^5}".format("cat"))

# string padding with center alignment
# and '*' padding character
print("{:*^5}".format("cat"))

cat  
  cat
 cat 
*cat*


In [124]:
# truncating strings to 3 letters
print("{:.3}".format("caterpillar"))

# truncating strings to 3 letters
# and padding
print("{:5.3}".format("caterpillar"))

# truncating strings to 3 letters,
# padding and center alignment
print("{:^5.3}".format("caterpillar"))

cat
cat  
 cat 


In [ ]:
Formatting class and dictionary members using format()

Python internally uses getattr() for class members in the form ".age". And, it uses __getitem__() lookup for dictionary members in the form "[index]".

In [125]:
# define Person class
class Person:
    age = 23
    name = "Adam"

# format age
print("{p.name}'s age is: {p.age}".format(p=Person()))

Adam's age is: 23


Here, Person object is passed as a keyword argument p.

Inside the template string, Person's name and age are accessed using .name and .age respectively.

In [126]:
# define Person dictionary
person = {'age': 23, 'name': 'Adam'}

# format age
print("{p[name]}'s age is: {p[age]}".format(p=person))

Adam's age is: 23


Similar to class, person dictionary is passed as a keyword argument p.

Inside the template string, person's name and age are accessed using [name] and [age] respectively.

There's an easier way to format dictionaries in Python using str.format(**mapping).

In [127]:
# define Person dictionary
person = {'age': 23, 'name': 'Adam'}

# format age
print("{name}'s age is: {age}".format(**person))

Adam's age is: 23


Arguments as format codes using format()

You can also pass format codes like precision, alignment, fill character as positional or keyword arguments dynamically.

In [132]:
# dynamic string format template
string = "{:{fill}{align}{width}}"

# passing format codes as arguments
print(string.format('cat', fill='*', align='^', width=5))

# dynamic float format template
num = "{:{align}{width}.{precision}f}"

# passing format codes as arguments
print(num.format(123.236, align='^',width=5, precision=2))

*cat*
123.24


Here,

In the first example, 'cat' is the positional argument is to be formatted. Likewise, fill='*', align='^' and width=5 are keyword arguments.

In the template string, these keyword arguments are not retrieved as normal strings to be printed but as the actual format codes fill, align and width.
The arguments replaces the corresponding named placeholders and the string 'cat' is formatted accordingly.

Likewise, in the second example, 123.236 is the positional argument and, align, width and precision are passed to the template string as format codes.

In [ ]:
Extra formatting options with format()

format() also supports type-specific formatting options like datetime's and complex number formatting.

format() internally calls __format__() for datetime, while format() accesses the attributes of the complex number.

You can easily override the __format__() method of any object for custom formatting.

In [133]:
import datetime
# datetime formatting
date = datetime.datetime.now()
print("It's now: {:%Y/%m/%d %H:%M:%S}".format(date))

# complex number formatting
complexNumber = 1+2j
print("Real part: {0.real} and Imaginary part: {0.imag}".format(complexNumber))

# custom __format__() method
class Person:
    def __format__(self, format):
        if(format == 'age'):
            return '23'
        return 'None'

print("Adam's age is: {:age}".format(Person()))

It's now: 2020/10/03 17:01:22
Real part: 1.0 and Imaginary part: 2.0
Adam's age is: 23


In [ ]:
Here,

For datetime:
Current datetime is passed as a positional argument to the format() method.
And, internally using __format__() method, format() accesses the year, month, day, hour, minutes and seconds.

For complex numbers:
1+2j is internally converted to a ComplexNumber object.
Then accessing its attributes real and imag, the number is formatted.

Overriding __format__():
Like datetime, you can override your own __format__() method for custom formatting which returns age when accessed as {:age}


In [ ]:
You can also use objects __str__() and __repr__() functionality with shorthand notations using format().

Like __format__(), you can easily override objects __str__() and __repr_() methods

In [134]:
# __str__() and __repr__() shorthand !r and !s
print("Quotes: {0!r}, Without Quotes: {0!s}".format("cat"))

# __str__() and __repr__() implementation for class
class Person:
    def __str__(self):
        return "STR"
    def __repr__(self):
        return "REPR"

print("repr: {p!r}, str: {p!s}".format(p=Person()))

Quotes: 'cat', Without Quotes: cat
repr: REPR, str: STR


Python String isalnum()
The isalnum() method returns True if all characters in the string are alphanumeric (either alphabets or numbers). If not, it returns False.

The syntax of isalnum() is:

string.isalnum()
isalnum() Parameters
The isalnum() doesn't take any parameters.

Return Value from isalnum()
The isalnum() returns:

True if all characters in the string are alphanumeric
False if at least one character is not alphanumeric

In [135]:
name = "M234onica"
print(name.isalnum())

# contains whitespace
name = "M3onica Gell22er "
print(name.isalnum())

name = "Mo3nicaGell22er"
print(name.isalnum())

name = "133"
print(name.isalnum())

True
False
True
True


In [136]:
name = "M0n1caG3ll3r"

if name.isalnum() == True:
   print("All characters of string (name) are alphanumeric.")
else:
    print("All characters are not alphanumeric.")

All characters of string (name) are alphanumeric.


Python String isalpha()
The isalpha() method returns True if all characters in the string are alphabets. If not, it returns False.

The syntax of isalpha() is:

string.isalpha()
isalpha() Parameters
isalpha() doesn't take any parameters.

Return Value from isalpha()
The isalpha() returns:

True if all characters in the string are alphabets (can be both lowercase and uppercase).
False if at least one character is not alphabet.


In [137]:
name = "Monica"
print(name.isalpha())

# contains whitespace
name = "Monica Geller"
print(name.isalpha())

# contains number
name = "Mo3nicaGell22er"
print(name.isalpha())

True
False
False


In [138]:
name = "MonicaGeller"

if name.isalpha() == True:
   print("All characters are alphabets")
else:
    print("All characters are not alphabets.")

All characters are alphabets


Python String isdecimal()
The isdecimal() method returns True if all characters in a string are decimal characters. If not, it returns False.

The syntax of isdecimal() is

string.isdecimal()
isdecimal() Parameters
The isdecimal() doesn't take any parameters.

Return Value from isdecimal()
The isdecimal() returns:

True if all characters in the string are decimal characters.
False if at least one character is not decimal character.


In [139]:
s = "28212"
print(s.isdecimal())

# contains alphabets
s = "32ladk3"
print(s.isdecimal())

# contains alphabets and spaces
s = "Mo3 nicaG el l22er"
print(s.isdecimal())

True
False
False


The superscript and subscripts are considered digit characters but not decimals. If the string contains these characters (usually written using unicode), isdecimal() returns False.

Similarly, roman numerals, currency numerators and fractions are considered numeric numbers (usually written using unicode) but not decimals. The isdecimal() also returns False in this case.

There are two methods isdigit() and isnumeric() that checks whether the string contains digit characters and numeric characters respectively.

Learn more about isdigit() and isnumeric() methods.

In [140]:
s = '23455'
print(s.isdecimal())

#s = '²3455'
s = '\u00B23455'
print(s.isdecimal())

# s = '½'
s = '\u00BD'
print(s.isdecimal())

True
False
False


Python String isdigit()
The isdigit() method returns True if all characters in a string are digits. If not, it returns False.

The syntax of isdigit() is

string.isdigit()
isdigit() Parameters
The isdigit() doesn't take any parameters.

Return Value from isdigit()
The isdigit() returns:

True if all characters in the string are digits.
False if at least one character is not a digit.


In [141]:
s = "28212"
print(s.isdigit())

# contains alphabets and spaces
s = "Mo3 nicaG el l22er"
print(s.isdigit())

True
False


A digit is a character that has property value:

Numeric_Type = Digit
Numeric_Type = Decimal

In Python, superscript and subscripts (usually written using unicode) are also considered digit characters. Hence, if the string contains these characters along with decimal characters, isdigit() returns True.

The roman numerals, currency numerators and fractions (usually written using unicode) are considered numeric characters but not digits. The isdigit() returns False if the string contains these characters.

To check whether a character is a numeric character or not, you can use isnumeric() method.

In [142]:
s = '23455'
print(s.isdigit())

#s = '²3455'
# subscript is a digit
s = '\u00B23455'
print(s.isdigit())

# s = '½'
# fraction is not a digit
s = '\u00BD'
print(s.isdigit())

True
True
False


Python String islower()
The islower() method returns True if all alphabets in a string are lowercase alphabets. If the string contains at least one uppercase alphabet, it returns False.

The syntax of islower() is:

string.islower()
islower() parameters
The islower() method doesn't take any parameters.

Return Value from islower()
The islower() method returns:

True if all alphabets that exist in the string are lowercase alphabets.
False if the string contains at least one uppercase alphabet.


In [143]:
s = 'this is good'
print(s.islower())

s = 'th!s is a1so g00d'
print(s.islower())

s = 'this is Not good'
print(s.islower())

True
True
False


In [144]:
s = 'this is good'
if s.islower() == True:
  print('Does not contain uppercase letter.')
else:
  print('Contains uppercase letter.')
  
s = 'this is Good'
if s.islower() == True:
  print('Does not contain uppercase letter.')
else:
  print('Contains uppercase letter.')

Does not contain uppercase letter.
Contains uppercase letter.


Python String isnumeric()
The isnumeric() method returns True if all characters in a string are numeric characters. If not, it returns False.

A numeric character has following properties:

Numeric_Type=Decimal
Numeric_Type=Digit
Numeric_Type=Numeric
In Python, decimal characters (like: 0, 1, 2..), digits (like: subscript, superscript), and characters having Unicode numeric value property (like: fraction, roman numerals, currency numerators) are all considered numeric characters.

You can write the digit and numeric characters using unicode in the program. For example:

s = '½'

s = '\u00BD'

The syntax of isnumeric() is
string.isnumeric()

isnumeric() Parameters
The isnumeric() method doesn't take any parameters.

Return Value from isnumeric()
The isnumeric() method returns:

True if all characters in the string are numeric characters.
False if at least one character is not a numeric character.


In [145]:
s = '1242323'
print(s.isnumeric())

#s = '²3455'
s = '\u00B23455'
print(s.isnumeric())

# s = '½'
s = '\u00BD'
print(s.isnumeric())

s = '1242323'
s='python12'
print(s.isnumeric())

True
True
True
False


In [146]:
#s = '²3455'
s = '\u00B23455'

if s.isnumeric() == True:
  print('All characters are numeric.')
else:
  print('All characters are not numeric.')

All characters are numeric.


Python String isupper()
The string isupper() method returns whether or not all characters in a string are uppercased or not.

The syntax of isupper() method is:

string.isupper()
String isupper() Parameters
The isupper() method doesn't take any parameters.

Return value from String isupper() 
The isupper() method returns:

True if all characters in a string are uppercase characters
False if any characters in a string are lowercase characters

In [147]:
# example string
string = "THIS IS GOOD!"
print(string.isupper());

# numbers in place of alphabets
string = "THIS IS ALSO G00D!"
print(string.isupper());

# lowercase string
string = "THIS IS not GOOD!"
print(string.isupper());

True
True
False


In [148]:
string = 'THIS IS GOOD'
if string.isupper() == True:
  print('Does not contain lowercase letter.')
else:
  print('Contains lowercase letter.')
  
string = 'THIS IS gOOD'
if string.isupper() == True:
  print('Does not contain lowercase letter.')
else:
  print('Contains lowercase letter.')

Does not contain lowercase letter.
Contains lowercase letter.


Python String istitle()
The istitle() returns True if the string is a titlecased string. If not, it returns False.

The syntax of istitle() method is:

string.istitle()
istitle() Parameters
The istitle() method doesn't take any parameters.

Return Value from istitle()
The istitle() method returns:

True if the string is a titlecased string
False if the string is not a titlecased string or an empty string

In [149]:
s = 'Python Is Good.'
print(s.istitle())

s = 'Python is good'
print(s.istitle())

s = 'This Is @ Symbol.'
print(s.istitle())

s = '99 Is A Number'
print(s.istitle())

s = 'PYTHON'
print(s.istitle())

True
False
True
True
False


In [150]:
s = 'I Love Python.'
if s.istitle() == True:
  print('Titlecased String')
else:
  print('Not a Titlecased String')
  
s = 'PYthon'
if s.istitle() == True:
  print('Titlecased String')
else:
  print('Not a Titlecased String')

Titlecased String
Not a Titlecased String


Python String isspace()
The isspace() method returns True if there are only whitespace characters in the string. If not, it return False.

Characters that are used for spacing are called whitespace characters. For example: tabs, spaces, newline, etc.

The syntax of isspace() is:

string.isspace()
isspace() Parameters
isspace() method doesn't take any parameters.

Return Value from isspace()
isspace() method returns:

True if all characters in the string are whitespace characters
False if the string is empty or contains at least one non-printable character

In [151]:
s = '   \t'
print(s.isspace())

s = ' a '
print(s.isspace())

s = ''
print(s.isspace())

True
False
False


In [152]:
s = '\t  \n'
if s.isspace() == True:
  print('All whitespace characters')
else:
  print('Contains non-whitespace characters')
  
s = '2+2 = 4'

if s.isspace() == True:
  print('All whitespace characters')
else:
  print('Contains non-whitespace characters.')

All whitespace characters
Contains non-whitespace characters.


In [ ]:
In built functions in python for str(sequence):
'__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',

# TUPLES

Tuples are immutable sequences of arbitrary objects. They are indexed by integers greater than zero. Tuples are hashable, which means we can sort lists of them and they can be used as keys to dictionaries. Syntactically, tuples are just a comma-separated sequence of values; however, it is common practice to enclose them in parentheses:

tpl= ('a', 'b', 'c')

It is important to remember to use a trailing comma when creating a tuple with one element, for example:

t = ('a',)

Without the trailing comma, this would be interpreted as a string.

We can also create a tuple using the built-in function tuple(). With no argument, this creates an empty tuple. 

If the argument to tuple() is a sequence then this creates a tuple of elements of that sequence, for example:

In [4]:
t = tuple('sequence')
t

('s', 'e', 'q', 'u', 'e', 'n', 'c', 'e')

In [9]:
# Indexing
print(t[0:3])
print(t[-3:-1])
print(t[-3:])

('s', 'e', 'q')
('n', 'c')
('n', 'c', 'e')


In [10]:
# Concatenate
t + ('and',)

('s', 'e', 'q', 'u', 'e', 'n', 'c', 'e', 'and')

In [11]:
# can use max, min , sum built in functions in tuple

In [14]:
# sort
x = sorted(t)
print(x)   # gives a list 

print(tuple(x)) # convert to tuple 


['c', 'e', 'e', 'e', 'n', 'q', 's', 'u']
('c', 'e', 'e', 'e', 'n', 'q', 's', 'u')


In [23]:
# Since tuple is a kind of object it can store a tuple within a tuple 
y = ('a','b',(1,2,3,'r'))
y[-1]  # a tuple in tuple 

(1, 2, 3, 'r')

In [24]:
dir(tuple)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

Python Tuple count()
The count() method returns the number of times the specified element appears in the tuple.

The syntax of the count() method is:

tuple.count(element)
count() Parameters
The count() method takes a single argument:

element - the element to be counted
Return value from count()
The count() method returns the number of times element appears in the tuple.

In [25]:
# vowels tuple
vowels = ('a', 'e', 'i', 'o', 'i', 'u')

# count element 'i'
count = vowels.count('i')

# print count
print('The count of i is:', count)

# count element 'p'
count = vowels.count('p')

# print count
print('The count of p is:', count)

The count of i is: 2
The count of p is: 0


In [26]:
# random tuple
random = ('a', ('a', 'b'), ('a', 'b'), [3, 4])

# count element ('a', 'b')
count = random.count(('a', 'b'))

# print count
print("The count of ('a', 'b') is:", count)

# count element [3, 4]
count = random.count([3, 4])

# print count
print("The count of [3, 4] is:", count)

The count of ('a', 'b') is: 2
The count of [3, 4] is: 1


Python Tuple index()
The index() method returns the index of the specified element in the tuple.

The syntax of the tuple index() method is:

tuple.index(element, start, end)

Tuple index() parameters
The tuple index() method can take a maximum of three arguments:

element - the element to be searched
start (optional) - start searching from this index
end (optional) - search the element up to this index

Return Value from Tuple index()
The index() method returns the index of the given element in the tuple.
If the element is not found, a ValueError exception is raised.
Note: The index() method only returns the first occurrence of the matching element.

In [27]:
# vowels tuple
vowels = ('a', 'e', 'i', 'o', 'i', 'u')

# index of 'e' in vowels
index = vowels.index('e')
print('The index of e:', index)

# element 'i' is searched
# index of the first 'i' is returned
index = vowels.index('i')

print('The index of i:', index)

The index of e: 1
The index of i: 2


In [28]:
# vowels tuple
vowels = ('a', 'e', 'i', 'o', 'u')

# index of'p' is vowels
index = vowels.index('p')
print('The index of p:', index)

ValueError: tuple.index(x): x not in tuple

In [29]:
# alphabets tuple
alphabets = ('a', 'e', 'i', 'o', 'g', 'l', 'i', 'u')

# index of 'i' in alphabets
index = alphabets.index('e')   # 2
print('The index of e:', index)

# 'i' after the 4th index is searched
index = alphabets.index('i', 4)   # 6
print('The index of i:', index)

# 'i' between 3rd and 5th index is searched
index = alphabets.index('i', 3, 5)   # Error!
print('The index of i:', index)

The index of e: 1
The index of i: 6


ValueError: tuple.index(x): x not in tuple

Most operators, such as those for slicing and indexing, work as they do on lists. However, because tuples are immutable, trying to modify an element of a tuple will give you a TypeError. We can compare tuples in the same way that we compare other sequences, using the ==, > and < operators.

An important use of tuples is to allow us to assign more than one variable at a time by placing a tuple on the left-hand side of an assignment, for example:

In [9]:
l = ('one', 'two')
x,y =l  # Unpacking a Tuple 
print(x+' '+y)
print(y)

one two
two


In [14]:
list_1 = [12,13,14,15]

w,x,y,z = list_1  # unpacking a list

print(w,x,y,z,sep='\t')

12	13	14	15


In [35]:
# swap
x,y = y,x 
print(x)
print(y)

two
one


# LISTS

Lists are probably the most used built-in data structures in Python because they can be composed of any number of other data types. They are a simple representation of arbitrary objects. Like strings, they are indexed by integers starting with zero.

When we are working with lists, and other container objects, it is important to understand the internal mechanism that Python uses to copy them. Python creates real copies only if it has to. When we assign the value of a variable to another variable, both of these variables point to the same memory location. A new slot in memory will only be allocated if one of the variables changes. This has important consequences for mutable compound objects such as lists. Consider the following code:

In [36]:
x=1;y=2;z=3
list1 = [x,y,z]
list2 = list1
list2[1]=4
list1

[1, 4, 3]

List Index
We can use the index operator [] to access an item in a list. In Python, indices start at 0. So, a list having 5 elements will have an index from 0 to 4.

Trying to access indexes other than these will raise an IndexError. The index must be an integer. We can't use float or other types, this will result in TypeError.

Nested lists are accessed using nested indexing.

In [1]:
# List indexing

my_list = ['p', 'r', 'o', 'b', 'e']

# Output: p
print(my_list[0])

# Output: o
print(my_list[2])

# Output: e
print(my_list[4])

# Nested List
n_list = ["Happy", [2, 0, 1, 5]]

# Nested indexing
print(n_list[0][1])

print(n_list[1][3])

# Error! Only integer can be used for indexing
print(my_list[4.0])

p
o
e
a
5


TypeError: list indices must be integers or slices, not float

Negative indexing
Python allows negative indexing for its sequences. The index of -1 refers to the last item, -2 to the second last item and so on.

In [2]:
# Negative indexing in lists
my_list = ['p','r','o','b','e']

print(my_list[-1])

print(my_list[-5])

e
p


How to slice lists in Python?
We can access a range of items in a list by using the slicing operator :(colon).

In [3]:
# List slicing in Python

my_list = ['p','r','o','g','r','a','m','i','z']

# elements 3rd to 5th
print(my_list[2:5])

# elements beginning to 4th
print(my_list[:-5])

# elements 6th to end
print(my_list[5:])

# elements beginning to end
print(my_list[:])

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


How to change or add elements to a list?
Lists are mutable, meaning their elements can be changed unlike string or tuple.

We can use the assignment operator (=) to change an item or a range of items.

In [4]:
# Correcting mistake values in a list
odd = [2, 4, 6, 8]

# change the 1st item    
odd[0] = 1            

print(odd)

# change 2nd to 4th items
odd[1:4] = [3, 5, 7]  

print(odd)                   

[1, 4, 6, 8]
[1, 3, 5, 7]


We can add one item to a list using the append() method or add several items using extend() method.

In [5]:
# Appending and Extending lists in Python
odd = [1, 3, 5]

odd.append(7)

print(odd)

odd.extend([9, 11, 13])

print(odd)

[1, 3, 5, 7]
[1, 3, 5, 7, 9, 11, 13]


In [ ]:
Operation

Result                                     Notes

s[i] = x                         item i of s is replaced by x

s[i:j] = t           slice of s from i to j is replaced by the contents of the                                            iterable t

del s[i:j]                            same as s[i:j] = []

s[i:j:k] = t       the elements of s[i:j:k] are replaced by those of t  (1)

del s[i:j:k]          removes the elements of s[i:j:k] from the list

s.append(x)          appends x to the end of the sequence (same as                                               s[len(s):len(s)] = [x])

s.clear()               removes all items from s (same as del s[:])   (5)

s.copy()                 creates a shallow copy of s (same as s[:])   (5)

s.extend(t) or s += t    extends s with the contents of t (for the most part                                 the same as s[len(s):len(s)] = t)

s *= n                   updates s with its contents repeated n times    (6)

s.insert(i, x)        inserts x into s at the index given by i (same as s[i:i]                                          = [x])

s.pop([i])            retrieves the item at i and also removes it from s  (2)

s.remove(x)          remove the first item from s where s[i] is equal to x (3)

s.reverse()                 reverses the items of s in place    (4)

Notes:

1.t must have the same length as the slice it is replacing.

2.The optional argument i defaults to -1, so that by default the last item is removed and returned.

3.remove() raises ValueError when x is not found in s.

4.The reverse() method modifies the sequence in place for economy of space when reversing a large sequence. To remind users that it operates by side effect, it does not return the reversed sequence.

5.clear() and copy() are included for consistency with the interfaces of mutable containers that don’t support slicing operations (such as dict and set). copy() is not part of the collections.abc.MutableSequence ABC, but most concrete mutable sequence classes provide it.

New in version 3.3: clear() and copy() methods.

6.The value n is an integer, or an object implementing __index__(). Zero and negative values of n clear the sequence. Items in the sequence are not copied; they are referenced multiple times, as explained for s * n under Common Sequence Operations.

We can also use + operator to combine two lists. This is also called concatenation.

The * operator repeats a list for the given number of times.

In [6]:
# Concatenating and repeating lists
odd = [1, 3, 5]

print(odd + [9, 7, 5])

print(["re"] * 3)

[1, 3, 5, 9, 7, 5]
['re', 're', 're']


Furthermore, we can insert one item at a desired location by using the method insert() or insert multiple items by squeezing it into an empty slice of a list.

In [7]:
# Demonstration of list insert() method
odd = [1, 9]
odd.insert(1,3)

print(odd)

odd[2:2] = [5, 7]

print(odd)

[1, 3, 9]
[1, 3, 5, 7, 9]


How to delete or remove elements from a list?

We can delete one or more items from a list using the keyword del. It can even delete the list entirely.

In [8]:
# Deleting list items
my_list = ['p', 'r', 'o', 'b', 'l', 'e', 'm']

# delete one item
del my_list[2]

print(my_list)

# delete multiple items
del my_list[1:5]

print(my_list)

# delete entire list
del my_list

# Error: List not defined
print(my_list)

['p', 'r', 'b', 'l', 'e', 'm']
['p', 'm']


NameError: name 'my_list' is not defined

In [12]:
list_1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20]

for index,number in enumerate(list_1):
    if (number < 5) or (number > 15):
        del list_1[index]

print(list_1)  # shows a wrong result

[2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20]


In [13]:
list_1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20]

for index in range(len(list_1)-1, -1 , -1):
    if (list_1[index]<5) or (list_1[index]>15):
        del list_1[index]
print(list_1)  # shows a right result

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [18]:
list_1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20]

top_index = len(list_1) -1 
for index,number in enumerate(reversed(list_1)):
    if (number<5) or (number>15):
        del list_1[top_index - index]
        
print(list_1)  # shows a right result

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


We can use remove() method to remove the given item or pop() method to remove an item at the given index.

The pop() method removes and returns the last item if the index is not provided. This helps us implement lists as stacks (first in, last out data structure).

We can also use the clear() method to empty a list.

In [9]:
my_list = ['p','r','o','b','l','e','m']
my_list.remove('p')

# Output: ['r', 'o', 'b', 'l', 'e', 'm']
print(my_list)

# Output: 'o'
print(my_list.pop(1))

# Output: ['r', 'b', 'l', 'e', 'm']
print(my_list)

# Output: 'm'
print(my_list.pop())

# Output: ['r', 'b', 'l', 'e']
print(my_list)

my_list.clear()

# Output: []
print(my_list)

['r', 'o', 'b', 'l', 'e', 'm']
o
['r', 'b', 'l', 'e', 'm']
m
['r', 'b', 'l', 'e']
[]


In [11]:
my_list = ['p','r','o','b','l','e','m']
my_list[2:3] = []
print(my_list)

my_list[2:5] = []
print(my_list)

['p', 'r', 'b', 'l', 'e', 'm']
['p', 'r', 'm']


Python List Methods
Methods that are available with list objects in Python programming are tabulated below.

They are accessed as list.method(). Some of the methods have already been used above.

In [ ]:
Python List Methods
append() - Add an element to the end of the list
extend() - Add all elements of a list to the another list
insert() - Insert an item at the defined index
remove() - Removes an item from the list
pop() - Removes and returns an element at the given index
clear() - Removes all items from the list
index() - Returns the index of the first matched item
count() - Returns the count of the number of items passed as an argument
sort() - Sort items in a list in ascending order
reverse() - Reverse the order of items in the list
copy() - Returns a shallow copy of the list

Iterating Through a List

Using a for loop we can iterate through each item in a list.

In [12]:
for fruit in ['apple','banana','mango']:
    print("I like",fruit)

I like apple
I like banana
I like mango


List Membership Test

We can test if an item exists in a list or not, using the keyword in.

In [13]:
my_list = ['p', 'r', 'o', 'b', 'l', 'e', 'm']

# Output: True
print('p' in my_list)

# Output: False
print('a' in my_list)

# Output: True
print('c' not in my_list)

True
False
True


List Comprehension: Elegant way to create new List
List comprehension is an elegant and concise way to create a new list from an existing list in Python.

A list comprehension consists of an expression followed by for statement inside square brackets.

Here is an example to make a list with each item being increasing power of 2.

In [14]:
pow2 = [2 ** x for x in range(10)]
print(pow2)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


In [16]:
#This code is equivalent to:

pow2 = []
for x in range(10):
    pow2.append(2 ** x)
print(pow2)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]


A list comprehension can optionally contain more for or if statements. An optional if statement can filter out items for the new list. Here are some examples.

In [17]:
pow2 = [2 ** x for x in range(10) if x > 5]
pow2

[64, 128, 256, 512]

In [18]:
odd = [x for x in range(20) if x % 2 == 1]
odd


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [19]:
[x+y for x in ['Python ','C '] for y in ['Language','Programming']]
['Python Language', 'Python Programming', 'C Language', 'C Programming']

['Python Language', 'Python Programming', 'C Language', 'C Programming']

In [37]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

Python List index()
The index() method returns the index of the specified element in the list.

The syntax of the list index() method is:

list.index(element, start, end)

list index() parameters
The list index() method can take a maximum of three arguments:

element - the element to be searched
start (optional) - start searching from this index
end (optional) - search the element up to this index

Return Value from List index()
The index() method returns the index of the given element in the list.
If the element is not found, a ValueError exception is raised.

Note: The index() method only returns the first occurrence of the matching element.

In [38]:
# vowels list
vowels = ['a', 'e', 'i', 'o', 'i', 'u']

# index of 'e' in vowels
index = vowels.index('e')
print('The index of e:', index)

# element 'i' is searched
# index of the first 'i' is returned
index = vowels.index('i')

print('The index of i:', index)

# alphabets list
alphabets = ['a', 'e', 'i', 'o', 'g', 'l', 'i', 'u']

# index of 'i' in alphabets
index = alphabets.index('e')   # 2
print('The index of e:', index)

# 'i' after the 4th index is searched
index = alphabets.index('i', 4)   # 6
print('The index of i:', index)

# 'i' between 3rd and 5th index is searched
index = alphabets.index('i', 3, 5)   # Error!
print('The index of i:', index)

The index of e: 1
The index of i: 2
The index of e: 1
The index of i: 6


ValueError: 'i' is not in list

Python List append()
The append() method adds an item to the end of the list.

The syntax of the append() method is:

list.append(item)

append() Parameters
The method takes a single argument

item - an item to be added at the end of the list
The item can be numbers, strings, dictionaries, another list, and so on.

Return Value from append()
The method doesn't return any value (returns None).

In [39]:
# animals list
animals = ['cat', 'dog', 'rabbit']

# 'guinea pig' is appended to the animals list
animals.append('guinea pig')

# Updated animals list
print('Updated animals list: ', animals)

Updated animals list:  ['cat', 'dog', 'rabbit', 'guinea pig']


In [40]:
#Example 2: Adding List to a List

# animals list
animals = ['cat', 'dog', 'rabbit']

# list of wild animals
wild_animals = ['tiger', 'fox']

# appending wild_animals list to the animals list
animals.append(wild_animals)

print('Updated animals list: ', animals)

Updated animals list:  ['cat', 'dog', 'rabbit', ['tiger', 'fox']]


It is important to notice that, a single item (wild_animals list) is added to the animals list in the above program.

If you need to add items of a list to another list (rather than the list itself), use the extend() method.

Python List extend()
The extend() method adds all the elements of an iterable (list, tuple, string etc.) to the end of the list.

The syntax of the extend() method is:

list1.extend(iterable)

Here, all the elements of iterable are added to the end of list1.

extend() Parameters
As mentioned, the extend() method takes an iterable such as list, tuple, string etc.

Return Value from extend()
The extend() method modifies the original list. It doesn't return any value

In [41]:
# language list
language = ['French', 'English']

# another list of language
language1 = ['Spanish', 'Portuguese']

# appending language1 elements to language
language.extend(language1)

print('Language List:', language)

Language List: ['French', 'English', 'Spanish', 'Portuguese']


In [4]:
#Example 2: Add Elements of Tuple and Set to List

# language list
language = ['French']

# language tuple
language_tuple = ('Spanish', 'Portuguese')

# language set
language_set = {'Chinese', 'Japanese'}

# appending language_tuple elements to language
language.extend(language_tuple)

print('New Language List:', language)

# appending language_set elements to language
language.extend(language_set)

print('Newer Language List:', language)

language.extend("HURRAY!")
print(language)

language.append("HURRAY!")
language

language.extend([100])
language

New Language List: ['French', 'Spanish', 'Portuguese']
Newer Language List: ['French', 'Spanish', 'Portuguese', 'Chinese', 'Japanese']
['French', 'Spanish', 'Portuguese', 'Chinese', 'Japanese', 'H', 'U', 'R', 'R', 'A', 'Y', '!']


['French',
 'Spanish',
 'Portuguese',
 'Chinese',
 'Japanese',
 'H',
 'U',
 'R',
 'R',
 'A',
 'Y',
 '!',
 'HURRAY!',
 100]

In [5]:
#Other Ways to Extend a List

#You can also append all elements of an iterable to the list using:

# 1. the + operator

a = [1, 2]
b = [3, 4]

a += b    # a = a + b


# Output: [1, 2, 3, 4]
print('a =', a)

a = a + 'abc'
print("new a is :",a)

# 2. the list slicing syntax

a = [1, 2]
b = [3, 4]

a[len(a):] = b

# Output: [1, 2, 3, 4]
print('a =', a)


a = [1, 2, 3, 4]


TypeError: can only concatenate list (not "str") to list

In [44]:
# Python extend() Vs append()

#If you need to add an element to the end of a list, you can use the 
# append() method.

a1 = [1, 2]
a2 = [1, 2]
b = (3, 4)

# a1 = [1, 2, 3, 4]
a1.extend(b) 
print(a1)

# a2 = [1, 2, (3, 4)]
a2.append(b)
print(a2)

[1, 2, 3, 4]
[1, 2, (3, 4)]


Python List insert()

The list insert() method inserts an element to the list at the specified index.

The syntax of the insert() method is

list.insert(i, elem)

Here, elem is inserted to the list at the ith index. All the elements after elem are shifted to the right.

insert() Parameters
The insert() method takes two parameters:

index - the index where the element needs to be inserted
element - this is the element to be inserted in the list
Notes:

If index is 0, the element is inserted at the beginning of the list.
If index is 3, the element is inserted after the 3rd element. Its position will be 4th.
Return Value from insert()
The insert() method doesn't return anything; returns None. It only updates the current list.

In [45]:
# vowel list
vowel = ['a', 'e', 'i', 'u']

# 'o' is inserted at index 3
# the position of 'o' will be 4th
vowel.insert(3, 'o')

print('Updated List:', vowel)

Updated List: ['a', 'e', 'i', 'o', 'u']


In [46]:
# Example 2: Inserting a Tuple (as an Element) to the List

mixed_list = [{1, 2}, [5, 6, 7]]

# number tuple
number_tuple = (3, 4)

# inserting a tuple to the list
mixed_list.insert(1, number_tuple)

print('Updated List:', mixed_list)

Updated List: [{1, 2}, (3, 4), [5, 6, 7]]


Python List remove()

The remove() method removes the first matching element (which is passed as an argument) from the list.

The syntax of the remove() method is:

list.remove(element)

remove() Parameters
The remove() method takes a single element as an argument and removes it from the list.
If the element doesn't exist, it throws ValueError: list.remove(x): x not in list exception.

Return Value from remove()
The remove() doesn't return any value (returns None).

In [47]:
# animals list
animals = ['cat', 'dog', 'rabbit', 'guinea pig']

# 'rabbit' is removed
animals.remove('rabbit')

# Updated animals List
print('Updated animals list: ', animals)

Updated animals list:  ['cat', 'dog', 'guinea pig']


In [48]:
# Example 2: remove() method on a list having duplicate elements

#If a list contains duplicate elements, the remove() method only removes 
#the first matching element.

# animals list
animals = ['cat', 'dog', 'dog', 'guinea pig', 'dog']

# 'dog' is removed
animals.remove('dog')

# Updated animals list
print('Updated animals list: ', animals)

Updated animals list:  ['cat', 'dog', 'guinea pig', 'dog']


Python List pop()
The pop() method removes the item at the given index from the list and returns the removed item.

The syntax of the pop() method is:

list.pop(index)

pop() parameters
The pop() method takes a single argument (index).
The argument passed to the method is optional. If not passed, the default index -1 is passed as an argument (index of the last item).

If the index passed to the method is not in range, it throws IndexError: pop index out of range exception.

Return Value from pop()
The pop() method returns the item present at the given index. This item is also removed from the list.

In [49]:
#Example 1: Pop item at the given index from the list

# programming languages list
languages = ['Python', 'Java', 'C++', 'French', 'C']

# remove and return the 4th item
return_value = languages.pop(3)
print('Return Value:', return_value)

# Updated List
print('Updated List:', languages)

Return Value: French
Updated List: ['Python', 'Java', 'C++', 'C']


Note: Index in Python starts from 0, not 1.

If you need to pop the 4th element, you need to pass 3 to the pop() method.

In [51]:
#Example 2: pop() without an index, and for negative indices
# programming languages list
languages = ['Python', 'Java', 'C++', 'Ruby', 'C']

# remove and return the last item
print('When index is not passed:') 
print('Return Value:', languages.pop())
print('Updated List:', languages)

# remove and return the last item
print('\nWhen -1 is passed:') 
print('Return Value:', languages.pop(-1))
print('Updated List:', languages)

# remove and return the third last item
print('\nWhen -3 is passed:') 
print('Return Value:', languages.pop(-3))
print('Updated List:', languages)

When index is not passed:
Return Value: C
Updated List: ['Python', 'Java', 'C++', 'Ruby']

When -1 is passed:
Return Value: Ruby
Updated List: ['Python', 'Java', 'C++']

When -3 is passed:
Return Value: Python
Updated List: ['Java', 'C++']


Python List count()
The count() method returns the number of times the specified element appears in the list.

The syntax of the count() method is:

list.count(element)
count() Parameters
The count() method takes a single argument:

element - the element to be counted
Return value from count()
The count() method returns the number of times element appears in the list.

In [52]:
# vowels list
vowels = ['a', 'e', 'i', 'o', 'i', 'u']

# count element 'i'
count = vowels.count('i')

# print count
print('The count of i is:', count)

# count element 'p'
count = vowels.count('p')

# print count
print('The count of p is:', count)

The count of i is: 2
The count of p is: 0


In [53]:
#Example 2: Count Tuple and List Elements Inside List

# random list
random = ['a', ('a', 'b'), ('a', 'b'), [3, 4]]

# count element ('a', 'b')
count = random.count(('a', 'b'))

# print count
print("The count of ('a', 'b') is:", count)

# count element [3, 4]
count = random.count([3, 4])

# print count
print("The count of [3, 4] is:", count)

The count of ('a', 'b') is: 2
The count of [3, 4] is: 1


Python List reverse()
The reverse() method reverses the elements of the list.

The syntax of the reverse() method is:

list.reverse()
reverse() parameter
The reverse() method doesn't take any arguments.

Return Value from reverse()
The reverse() method doesn't return any value. It updates the existing list.

In [54]:
# Operating System List
systems = ['Windows', 'macOS', 'Linux']
print('Original List:', systems)

# List Reverse
systems.reverse()

# updated list
print('Updated List:', systems)

Original List: ['Windows', 'macOS', 'Linux']
Updated List: ['Linux', 'macOS', 'Windows']


In [55]:
#Example 2: Reverse a List Using Slicing Operator

# Operating System List
systems = ['Windows', 'macOS', 'Linux']
print('Original List:', systems)

# Reversing a list	
#Syntax: reversed_list = systems[start:stop:step] 
reversed_list = systems[::-1]

# updated list
print('Updated List:', reversed_list)

Original List: ['Windows', 'macOS', 'Linux']
Updated List: ['Linux', 'macOS', 'Windows']


In [56]:
#Example 3: Accessing Elements in Reversed Order

#If you need to access individual elements of a list in the reverse order, 
#it's better to use reversed() function.

# Operating System List
systems = ['Windows', 'macOS', 'Linux']

# Printing Elements in Reversed Order
for i in reversed(systems):
    print(i)

Linux
macOS
Windows


In [16]:
L = [1,2,3,4,5,6,7,8]

for index, number in enumerate(reversed(L)):
    print(index,'-',number, end=';')

0 - 8;1 - 7;2 - 6;3 - 5;4 - 4;5 - 3;6 - 2;7 - 1;

Python List sort()

The sort() method sorts the elements of a given list in a specific ascending or descending order.

The syntax of the sort() method is:

list.sort(key=..., reverse=...)

Alternatively, you can also use Python's built-in sorted() function for the same purpose.

sorted(list, key=..., reverse=...)
Note: The simplest difference between sort() and sorted() is: sort() changes the list directly and doesn't return any value, while sorted() doesn't change the list and returns the sorted list.

sort() Parameters
By default, sort() doesn't require any extra parameters. However, it has two optional parameters:

reverse - If True, the sorted list is reversed (or sorted in Descending order)
key - function that serves as a key for the sort comparison
Return value from sort()
The sort() method doesn't return any value. Rather, it changes the original list.

If you want a function to return the sorted list rather than change the original list, use sorted().

In [57]:
# vowels list
vowels = ['e', 'a', 'u', 'o', 'i']

# sort the vowels
vowels.sort()

# print vowels
print('Sorted list:', vowels)

Sorted list: ['a', 'e', 'i', 'o', 'u']


Sort in Descending order
The sort() method accepts a reverse parameter as an optional argument.

Setting reverse = True sorts the list in the descending order.

list.sort(reverse=True)
Alternately for sorted(), you can use the following code.

sorted(list, reverse=True)

In [58]:
# vowels list
vowels = ['e', 'a', 'u', 'o', 'i']

# sort the vowels
vowels.sort(reverse=True)

# print vowels
print('Sorted list (in Descending):', vowels)

Sorted list (in Descending): ['u', 'o', 'i', 'e', 'a']


Sort with custom function using key

If you want your own implementation for sorting, the sort() method also accepts a key function as an optional parameter.

Based on the results of the key function, you can sort the given list.

list.sort(key=len)

Alternatively for sorted:

sorted(list, key=len)

Here, len is the Python's in-built function to count the length of an element.

The list is sorted based on the length of each element, from lowest count to highest.

We know that a tuple is sorted using its first parameter by default. Let's look at how to customize the sort() method to sort using the second element.

In [59]:
#Example 3: Sort the list using key

# take second element for sort
def takeSecond(elem):
    return elem[1]

# random list
random = [(2, 2), (3, 4), (4, 1), (1, 3)]

# sort list with key
random.sort(key=takeSecond)

# print list
print('Sorted list:', random)

Sorted list: [(4, 1), (2, 2), (1, 3), (3, 4)]


In [11]:
s = ' Abdgfejsz'
s_1 = sorted(s,key=str.casefold)
print(s_1)

s_2 = s.strip()
print(s_2)

s_2 = sorted(s_2, key=str.casefold)
print(s_2)

[' ', 'A', 'b', 'd', 'e', 'f', 'g', 'j', 's', 'z']
Abdgfejsz
['A', 'b', 'd', 'e', 'f', 'g', 'j', 's', 'z']


In [60]:
# sorting using custom key
employees = [
    {'Name': 'Alan Turing', 'age': 25, 'salary': 10000},
    {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000},
    {'Name': 'John Hopkins', 'age': 18, 'salary': 1000},
    {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000},
]

# custom functions to get employee info
def get_name(employee):
    return employee.get('Name')


def get_age(employee):
    return employee.get('age')


def get_salary(employee):
    return employee.get('salary')


# sort by name (Ascending order)
employees.sort(key=get_name)
print(employees, end='\n\n')

# sort by Age (Ascending order)
employees.sort(key=get_age)
print(employees, end='\n\n')

# sort by salary (Descending order)
employees.sort(key=get_salary, reverse=True)
print(employees, end='\n\n')

[{'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'John Hopkins', 'age': 18, 'salary': 1000}, {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}]

[{'Name': 'John Hopkins', 'age': 18, 'salary': 1000}, {'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}]

[{'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}, {'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'Name': 'John Hopkins', 'age': 18, 'salary': 1000}]



In [61]:
# sorting using custom key
employees = [
    {'Name': 'Alan Turing', 'age': 25, 'salary': 10000},
    {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000},
    {'Name': 'John Hopkins', 'age': 18, 'salary': 1000},
    {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000},
]

# sort by name (Ascending order)
employees.sort(key=lambda x: x.get('Name'))
print(employees, end='\n\n')

# sort by Age (Ascending order)
employees.sort(key=lambda x: x.get('age'))
print(employees, end='\n\n')

# sort by salary (Descending order)
employees.sort(key=lambda x: x.get('salary'), reverse=True)
print(employees, end='\n\n')

[{'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'John Hopkins', 'age': 18, 'salary': 1000}, {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}]

[{'Name': 'John Hopkins', 'age': 18, 'salary': 1000}, {'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}]

[{'Name': 'Mikhail Tal', 'age': 40, 'salary': 15000}, {'Name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'Name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'Name': 'John Hopkins', 'age': 18, 'salary': 1000}]



In [64]:
old_list = [1, 2, 3]
new_list = old_list
new_list

[1, 2, 3]

In [65]:

#The problem with copying lists in this way is that if you modify new_list, 
#old_list is also modified.

old_list = [1, 2, 3]
new_list = old_list

# add an element to list
new_list.append('a')

print('New List:', new_list)
print('Old List:', old_list)

New List: [1, 2, 3, 'a']
Old List: [1, 2, 3, 'a']


In [70]:
# mixed list
my_list = ['cat', 0, 6.7]

# copying a list
new_list = my_list.copy()
new_list.append('dog')
print('Copied List:', new_list)
print('Original list:', my_list)

Copied List: ['cat', 0, 6.7, 'dog']
Original list: ['cat', 0, 6.7]


In [67]:
# Example 2: Copy List Using Slicing Syntax

# shallow copy using the slicing syntax

# mixed list
list = ['cat', 0, 6.7]

# copying a list using slicing
new_list = list[:]

# Adding an element to the new list
new_list.append('dog')

# Printing new and old list
print('Old List:', list)
print('New List:', new_list)

Old List: ['cat', 0, 6.7]
New List: ['cat', 0, 6.7, 'dog']


In [71]:
# Defining a list
list = [{1, 2}, ('a'), ['1.1', '2.2']]

# clearing the list
list.clear()

print('List:', list)

List: []


In [72]:
#Example 2: Emptying the List Using del

# Defining a list
list = [{1, 2}, ('a'), ['1.1', '2.2']]

# clearing the list
del list[:]

print('List:', list)

List: []


In [40]:
# index vs enumerate 

list_1 =["mouse",
      "keyboard",
      "monitor",
      "camera",
      "usb chord",
      "mobile phone"]

for items in list_1:
    print(list_1.index(items))
    
for number, item in enumerate(list_1):
    print("{}:{}".format(number,item))
    
for index, character in enumerate("abcdefgh"):
    print(index,character)
    


0
1
2
3
4
5
0:mouse
1:keyboard
2:monitor
3:camera
4:usb chord
5:mobile phone
0 a
1 b
2 c
3 d
4 e
5 f
6 g
7 h


In [11]:
#NOTE:

# PRINT PROPERTY

list_1 = [11,43,56,57,67,98]

for index, value in enumerate(list_1):
    print(index,value, sep= ':' , end='\t\t')
    print(index, value**2,sep=':' ,end ='\n')
    print()

0:11		0:121

1:43		1:1849

2:56		2:3136

3:57		3:3249

4:67		4:4489

5:98		5:9604

